#!/bin/bash
export BUILD_LIBDIR=${CCCDIR}/usr/lib/${CCCBIN}
mkdir -p $CCCDIR/usr/lib/$CCCBIN

. $CCCDIR/usr/bin/_init_build_env.sh

if [ -z "$MSYSTEM" ]; then  
    build.exe -dunix @ccc.bld
else
    build.exe -dwindows @ccc.bld
fi
