#!/bin/bash
export BUILD_LIBDIR=${CCCDIR}/usr/lib/${CCCBIN}
mkdir -p $CCCDIR/usr/lib/$CCCBIN 

. $CCCDIR/usr/bin/_init_build_env.sh
export BUILD_OBJ="$BUILD_OBJ"_ui_


if [ -z "$MSYSTEM" ]; then  
    build.exe -dui_/unix @ui_.bld
else
    build.exe -dui_/windows @ui_.bld
fi
