#!/bin/bash
export BUILD_LIBDIR=${CCCDIR}/usr/lib/${CCCBIN}
mkdir -p $CCCDIR/usr/lib/$CCCBIN 

. $CCCDIR/usr/bin/_init_build_env.sh
export BUILD_OBJ="$BUILD_OBJ"_uic

# nincs kulon unix/windows valtozat

build.exe @uic.bld
