#!/bin/bash

# valasztas a fejlesztoeszkoz keszletek kozott
# ha az MSYS2 terminalt a start menubol inditjuk
# akkor ezek valamelyike be van allitva


# MINGW_PACKAGE_PREFIX=mingw-w64-x86_64           # gcc
# MINGW_PACKAGE_PREFIX=mingw-w64-ucrt-x86_64      # gcc, modernebb (UCRT) konyvtarak
# MINGW_PACKAGE_PREFIX=mingw-w64-clang-x86_64     # clang, mas konyvtarak, mas linker

set -x

pacman -Syu --needed \
    $MINGW_PACKAGE_PREFIX-gcc\
    $MINGW_PACKAGE_PREFIX-gtk3\
    $MINGW_PACKAGE_PREFIX-openssl\
    $MINGW_PACKAGE_PREFIX-pcre\
    $MINGW_PACKAGE_PREFIX-pcre2\
    $MINGW_PACKAGE_PREFIX-pkgconf\
    