#!/bin/bash

cp -p bashrcx  ~/
cp -p envccc   ~/

if   [[ $(uname) == Linux   ]]; then
    :
elif [[ $(uname) == FreeBSD ]]; then
    :
elif [[ $(uname) == NetBSD  ]]; then
    mkdir -p ~/bin
    cp -p sha256sum ~/bin
elif [[ $(uname) == SunOS   ]]; then
    :
else
    echo unknown OS: $(uname)
    exit 1
fi

mkdir -p ~/.temp
mkdir -p ~/.z

if ! (grep '. ~/bashrcx' ~/.bashrc 1>/dev/null 2>/dev/null); then
    echo >>~/.bashrc
    echo '. ~/bashrcx' >> ~/.bashrc
fi
