#!/bin/bash


if [ "$CCCVER" == "2"  ];then
    :;#ok
elif [ "$CCCVER" == "3"  ];then
    :;#ok
elif test -f $CCCDIR/usr/lib/ccc2.lib; then
    export CCCVER=2
elif test -f $CCCDIR/usr/lib/ccc3.lib; then
    export CCCVER=3
else
    echo Cannot detect CCC version.
    exit 1
fi

c++app.sh @parfilex.bld


