#!/bin/bash

LEMON_PATH=$CCCDIR/usr/bin/$CCCUNAME
LEMON_EXE=$LEMON_PATH/lemon.exe


if [ ! -x $LEMON_EXE ]; then
    cc  -I .  lemon.c  -o $LEMON_EXE
    cp -p lempar.c  $LEMON_PATH/

    if [ -x $LEMON_EXE ]; then
        echo 'lemon compiled successfully'
    else
        echo 'lemon failed to compile'
    fi
fi


