#!/bin/bash

#default
#fekete alapon fehér
#export ZCOLOR_0=w/n             #text
#export ZCOLOR_1=w/bg,n/w        #header, alert, get
#export ZCOLOR_2=bg/w            #mark
#export ZCOLOR_3=w/b,b/w         #alertbutton

#fehér alapon kék
export ZCOLOR_0=b/w             #text
export ZCOLOR_2=w/b             #mark

export CCCTERM_SIZE=80x52
export CCCTERM_FONTSPEC=-misc-fixed-medium-r-normal--15-140-75-75-c-90-iso10646-1
#export CCCTERM_FONTSPEC=-misc-console-medium-r-normal--16-160-72-72-c-80-iso10646-1

z.exe "$@" &
