#!/bin/bash

export OREF_SIZE=200000
                        
export ZCOLOR_0=n/w             #text
export ZCOLOR_1=n/rg,n/w        #header, alert, get 
export ZCOLOR_2=w/br            #mark
export ZCOLOR_3=w+/n            #alertbutton 

                       

if  echo "$CCCTERM_CONNECT" | grep "SOCKET:" >/dev/null; then
    export ZCOLOR_0=w/b         #text
    export ZCOLOR_1=b/w,w/b     #header, alert, get  
    export ZCOLOR_2=b/w         #mark
    export ZCOLOR_3=w+/n        #alertbutton
else    
    export CCCTERM_CONNECT="$CCCDIR/usr/bin/$CCCUNAME/ncterm.exe" 
    export CCCTERM_INHERIT=yes
fi

z.exe "$@"
