#!/bin/bash

rm -f   *.say *.pge *.wro *.out

 msk2say.exe         proba       ; mv proba.say     proba__m.say
 msk2pge.exe         proba       ; mv proba.pge     proba___.pge
 msk2pge.exe  -r     proba       ; mv proba.pge     proba__r.pge
 pge2wro.exe         proba___    #                  proba___.wro
 pge2out.exe  -gOUT  proba___    #                  proba___.out
 pge2out.exe  -gSAY  proba___    ; mv proba___.say  proba__p.say
