#!/bin/bash

( cd ../codegen && m && run.exe )

mkdir -p ${BUILD_OBJ}
pkg-config --cflags gtk+-2.0  >${BUILD_OBJ}/gtk-cflags
pkg-config --libs   gtk+-2.0  >${BUILD_OBJ}/gtk-libs
echo -Wno-deprecated-declarations >>${BUILD_OBJ}/gtk-cflags

export BUILD_LIBDIR=${CCCDIR}/usr/lib

cccapp.sh  @gtk.bld  -sccc3_gtk

if test -s error; then
    list error &
fi

cp -pf `pwd`/include/gtk.ch     $CCCDIR/usr/include/gtk.ch
cp -pf `pwd`/include/gdk.ch     $CCCDIR/usr/include/gdk.ch
cp -pf `pwd`/include/cccgtk.h   $CCCDIR/usr/include/cccgtk.h
cp -pf `pwd`/include/gdkkey.ch  $CCCDIR/usr/include/gdkkey.ch

