#!/bin/bash
#export SCRIPT=$CCCDIR/usr/tex/script
export SCRIPT=$(pwd)/script
 
#$SCRIPT/thtm.b $1
#$SCRIPT/tdvi.b $1

$SCRIPT/thtm.b ccc-belulrol.tex
cp html/ccc-belulrol.html ~/ADMIN/okhttpd/htdocs/ccc3

