#!/bin/bash

# Egy szokásos 
#       Ubuntu Precise 
#       Debian Wheezy
# telepítés után
# ezeket a csomagokat kell felrakni,
# hogy a CCC2/CCC3 leforduljon.

sudo apt-get install \
    g++ \
    libncurses5-dev \
    libncursesw5-dev \
    manpages-dev \
    glibc-doc \
    libx11-dev \
    libxft-dev \
    libssl-dev \
    libpcre3-dev \
    libreadline6-dev \
    git-core


#    libgtk2.0-dev \
#    libpangox-1.0-dev \

