#!/bin/bash
export EDITOR=z.exe
#set -x

git-add .

git-commit --all -m "tbrowse stabilize javítva"

# "terminal invalidate szinkronizálva"
# "ppo2cpp 5.0.13 vararg API bővítve, method forwarding átdolgozva" #2009.04.28
# "ppo2cpp 5.0.12: method forwarding" #2009.04.22
# "jt: cellaeditor számok változása, picturedocument R flag" #2009.03.15
# "sql2: mkentitylib code_generated" #2009.03.15
# "sql2: where x in :1" #2009.02.24
# "xstart: hdup -> sethandleinhertflag" #2009.02.17
# "jterminal 1.1.12, jtconnect hibaágak kidolgozása" #2009.02.05
# "sslcon_accept-ben timeout (default: 10 sec)" #2009.02.05
# "bovitett simplehash osztaly" #2009.01.20
# "prg2ppo 1.4.0.rc1" #2009.01.12
# "tex" #2009.01.12
# "tutor qsort" #2008.12.23
# "gtk javitgatas" #2008.12.15
# "szalkezeles javitva" #2008.12.10
# "Windows terminal FreeConsole" #2008.12.10
# "GTK warnings" #2008.12.10
# "delete -> DELTHRDATA" #2008.12.10
# "closeonexec/sethandleinheritflag egysegesites" #2008.12.10
# "SIGABRT kezeles" #2008.12.10
# "ccc portok frissites" #2008.12.10
# "unix-ncurses terminál" #2008.11.12
# "telepitokeszlet frissites" #2008.11.05
# "tovabbi gcc 4.3.2 warningok (flex)" #2008.11.05
# "clean-all.b javitva" #2008.11.04
# "gcc 4.3.2 warningok elnyomva" #2008.11.04
# "qsort demó" #2008.11.04
# "terminal expose event" #2008.10.21
# "savex time korrekcio" #2008.09.17
# "postfix comment"
