#!/bin/bash

# 1
# work <--> index  (changes in the working tree not yet indexed)
# git diff | less

# 2
# index <--> last commit (what would be committed on "git commit")
# git diff --cached | less

# 3
# work <--> last commit (what would be committed on "git -a commit")
git diff HEAD | less -S
