#!/bin/bash

# a working tree eltérése az utolsó committól

echo
echo '#-----------------------------------'

git add --all        # frissíti a staging indexet
git diff  HEAD       # a staging index eltérése az utolsó committól

