#!/bin/bash

git-status | grep "nothing to commit" | if ! read GREPOUT; then
    mv   COMMIT-LIST COMMIT-SAVE
    echo ============================= >COMMIT-LIST
    date >>COMMIT-LIST
    cat  COMMIT >>COMMIT-LIST
    echo >>COMMIT-LIST
    echo >>COMMIT-LIST
    cat  COMMIT-SAVE >>COMMIT-LIST
    rm   COMMIT-SAVE
fi

git-add .                   # mod new
git-commit -a -F COMMIT     # mod del

git-push  --all
