#!/bin/bash
# pull előtt célszerű commitolni 
# másképp egy sikertelen merge olyan hibás állapotra vezethet
# amiből nehéz kikeveredni

./g-commit

echo
echo '#-----------------------------------'

git pull

