#!/bin/bash

#1) törli az összes .gitignored fájlt
#2) átlinkeli az .git/local-ban levő scripteket
#
#
# Az a koncepció, .git/local-ban egyéni scriptek vannak
# amelyek mind ignoráltak, ezért  git clean -fXd törli őket
# az objectekkel es exekkel együtt, de csak a gyökérben
# levő linkjüket, a .git/local-ban levő tényleges fájlt nem.
# A második lépésben aztán újra belinkelődnek a gyökérbe.


git clean -fXd  2>&1 >/dev/null

if [ -d .git/local  ];then
    for loc in .git/local/* ;do
        rm -f $(basename $loc)
        ln -s $loc  .
    done
fi

