#!/bin/bash

# merge-elni úgy kell, hogy
#   commitoljuk a devel ágat (git st üreset ad)
#   ráállunk a master ágra (gn -> set branch master )

 git merge devel

# ez beolvasztja develt a masterba
# ellenorizni kell a conflict-okat
# egy conflict így néz ki:
#
#<<<<<<< HEAD
#    master version
#    master version
#    master version
#=======
#    devel version
#    devel version
#    devel version
#>>>>>>> devel
#
# ki kell javitani a forrásokat a conflict-oknál
# és újra commitolni, ezután a devel ág megszüntethető

# Hogy néz ki az a conflict, ami úgy keletkezik,
# hogy az egyik ág mődosít egy fájlt,
# miközben egy másik ág törli?




git branch -d devel


# majd miután rendbehoztuk a conflict-okat
# új devel ágat csinálunk, és abban dolgozunk tovább.

# git branch devel

