#!/bin/bash
#set -x

source make_verf 3

#-------------------
# initial setup
#-------------------

( cd setup/setup-flex && m )
if ! flex.exe -V; then
    echo "flex.exe not installed"
    echo "install flex then run install.b again"
    exit 1
fi    

( cd setup/setup-lemon && m )
if ! lemon.exe -x; then
    echo "lemon.exe not installed"
    echo "install lemon then run install.b again"
    exit 1
fi    


if [[ $CCCUNAME == msys2 ]];then
  ( cd setup/setup-windows && m ) 
else
  ( cd setup/setup-unix && m ) 
fi

if ! build.exe -v; then
    echo "build.exe not installed"
    echo "initial setup failed"
    exit 1
fi    
if ! prg2ppo.exe -v; then
    echo "prg2ppo.exe not installed"
    echo "initial setup failed"
    exit 1
fi    
if ! removecr.exe -x; then
    echo "removecr.exe not installed"
    echo "initial setup failed"
    exit 1
fi    


( cd ccctools/ppo2cpp && m )
if ! ppo2cpp.exe -v; then
    echo "ppo2cpp.exe not installed"
    echo "initial setup failed"
    exit 1
fi    


#-------------------
# ccclib
#-------------------

( cd ccclib && m )

#-------------------
# ccctools
#-------------------
 
( cd ccctools/cccbn     && m )
( cd ccctools/build     && m )
( cd ccctools/prg2ppo   && m )
( cd ccctools/removecr  && m )

if [ "$CCCUNAME" == msys2 ]; then
    :
else
    ( cd ccctools/elfapp    && m )
    ( cd ccctools/mklink    && m )
fi

#-------------------
# terminal
#-------------------

if [ "$CCCUNAME" == msys2 ]; then
    ( cd terminal/windows && m )
    ( cd terminal/windows-cterm && m )
else
    ( cd terminal/unix && m )
    ( cd terminal/unix-cterm && m )
fi

( cd terminal/sslforw       && m )

if test -f /usr/include/gtk-2.0/gtk/gtk.h; then
    ( cd terminal/gtk2 && m )
fi

if test -f /usr/include/gtk-3.0/gtk/gtk.h; then
    ( cd terminal/gtk3 && m )
fi


#-------------------
# msk2say
#-------------------

( cd tools/mask && m )


#-------------------
# tools
#-------------------

( cd tools/crypto           && m )
( cd tools/dirsync          && m )
( cd tools/list             && m )
( cd tools/pcre2            && m )                               
( cd tools/regex            && m )
( cd tools/socket           && m )
( cd tools/textview         && m )                            
( cd tools/xmldom           && m )
( cd tools/xstart           && m )
( cd tools/z                && m )
( cd tools/zlib             && m )


