#!/bin/bash
#set -x


if [ -n "$MSYSTEM"  ];then
    if [ "${MSYSTEM}" == "MINGW64" ]; then
        : ok
    elif [ "${MSYSTEM}" == "UCRT64" ]; then
        : ok
    elif [ "${MSYSTEM}" == "CLANG64" ]; then
        : ok
    else
        echo "required msys2 subsystem: MINGW64/CLANG64/UCRT64"
        exit 1
    fi
    
    if [ "${MINGW_PREFIX}" == "" ]; then
        # ha be van allitva MSYSTEM
        # akkor az msys2 beallitja MINGW_PREFIX-et
        #   MSYS    -> MINGW_PREFIX=/usr
        #   MINGW64 -> MINGW_PREFIX=/mingw64
        #   UCRT64  -> MINGW_PREFIX=/ucrt64
        echo MSYSTEM=${MSYSTEM}
        echo MINGW_PREFIX variable not set
        exit 1
    fi
    
    if ! test -x ${MINGW_PREFIX}/bin/c++; then
        echo c++ compiler not configured
        echo MSYSTEM=${MSYSTEM}
        echo MINGW_PREFIX=${MINGW_PREFIX}
        which c++
        exit 1
    fi
fi



if [ "${CCCVER}" != "$1" ]; then
    echo "CCCVER (=${CCCVER}) environment variable not properly set"
    exit 1
fi

touch cccdir
if [ ! $CCCDIR/cccdir -ef cccdir ]; then
    rm  cccdir
    echo "script must start from CCCDIR as working directory"
    exit 1
else
    rm cccdir
fi

if  ! test -f ./usr/build/prg2obj.bld; then
    echo "CCCDIR/usr/build/prg2obj.bld not found"
    echo "CCCDIR (=${CCCDIR}) environment variable not properly set"
    exit 1
fi

if  ! test -f ./usr/options/$CCCUNAME/$CCCBIN/compile.opt; then
    echo "CCCDIR/usr/options/CCCUNAME/CCCBIN/compile.opt not found"
    echo "CCCBIN(=${CCCBIN}) environment variable not properly set"
    exit 1
fi

. _cpp_version.sh
