#!/bin/bash

source make_verf 3

#-------------------
# tabobj
#-------------------

( cd tabobj/tbbtbtx && m )


#-------------------
# tools
#-------------------

( cd jt/jtlib               &&  m)

( cd tools/dbaseiii         && m )
( cd tools/dbfview          && m )
( cd tools/json             && m )                                
( cd tools/pcre             && m )                                
( cd tools/regex            && m )
( cd tools/setperm          && m )
( cd tools/smtp_client      && m )
( cd tools/sql2             && m )
( cd tools/stomp            && m )
( cd tools/tdc2prg          && m )
( cd tools/tdccmp           && m )
( cd tools/tran2cpp         && m )
( cd tools/websrv           && m )
( cd tools/xmlrpc           && m )
( cd tools/zgrep            && m )

( cd tutor/fpath            && m )
( cd tutor/rename           && m )



