#!/bin/bash

# linux bash script
if [ "${MSYSTEM}" == "MSYS" ]; then
    echo "script cannot run in MSYS2"
    exit 1
fi


if [ "${CCCVER}" != "$1" ]; then
    echo "CCCVER (=${CCCVER}) environment variable not properly set"
    exit 1
fi

touch cccdir
if [ ! $CCCDIR/cccdir -ef cccdir ]; then
    rm cccdir
    echo "script must start from CCCDIR as working directory"
    exit 1
else
    rm cccdir
fi

if  ! test -f ./usr/bin/$CCCUNAME/__unix.b; then
    echo "CCCDIR/usr/bin/CCCUNAME/__unix.b not found"
    echo "CCCUNAME (=${CCCUNAME}) environment variable not properly set"
    exit 1
fi

if  ! test -f ./usr/options/$CCCBIN/compile.opt; then
    echo "CCCDIR/usr/options/CCCBIN/compile.opt not found"
    echo "CCCBIN (=${CCCBIN}) environment variable not properly set"
    exit 1
fi

. cppver.b
