#!/bin/bash

grep lgc            usr/options/lin/link.opt
echo

grep MULTITHREAD    usr/options/lin/compile.opt
grep GC_BOEHM       usr/options/lin/compile.opt
grep GC_NATIVE      usr/options/lin/compile.opt
echo

