#!/bin/bash
#példa a használatra

#1. bt-ből tds
bt2tds.exe /opt/konto/kdemo/bank.bt -p bankfiok  -t konto.bank 

#2. import a bt-ből a tds alapján
btimport.exe -d P  -e bank.tds -f /opt/konto/kdemo/bank.bt

#3. SQL tábla editálás ugyanazon tds alapján
jeed bank.tds

