#!/bin/bash
#példa a használatra

#1. bt-ből tds
bt2tds.exe  /opt/konto/kdemo/betet.bt  -p szerzszam  -t konto.betet

#2. import a bt-ből a tds alapján
btimport.exe  -d P  -e betet.tds  -f /opt/konto/kdemo/betet.bt

#3. SQL tábla editálás ugyanazon tds alapján
jeed betet.tds

