#!/bin/bash

if ! [ -f /usr/include/X11/Xlib.h ]; then
    exit 0
fi
if [ "$CCCVER" == "2"  ];then
    :;#ok
elif [ "$CCCVER" == "3"  ];then
    :;#ok
elif test -f $CCCDIR/usr/lib/ccc2.lib; then
    export CCCVER=2
elif test -f $CCCDIR/usr/lib/ccc3.lib; then
    export CCCVER=3
else
    echo Cannot detect CCC version.
    exit 1
fi

c++app.sh @parfile.bld

