#define EXPR                            1
#define SPACE                           2
#define EXCL                            3
#define MINUS                           4
#define PLUS                            5
#define AT                              6
#define LBRACKET                        7
#define RBRACKET                        8
#define SLASH                           9
#define BSLASH                         10
#define DOT                            11
#define STAR                           12
#define MODULO                         13
#define POWER                          14
#define DOLLAR                         15
#define GT                             16
#define LT                             17
#define COLON                          18
#define EQUAL                          19
#define LPAR                           20
#define RPAR                           21
#define DOTDOT                         22
#define LBRACE                         23
#define RBRACE                         24
#define PIPE                           25
#define COMMA                          26
