#!/bin/bash

bapp_unix0.b -d. -sccc"$CCCVER"_socket

cp -pf obj$CCCBIN/*.lib  $CCCDIR/usr/lib/$CCCBIN
#cp -pf obj$CCCBIN/*.so  $CCCDIR/usr/lib/$CCCBIN


#so kozvetlen cp helyett mv-vel kerul a helyere,
#hogy az eppen futo programok nem szalljanak el
find obj$CCCBIN/*.so | while read so; do
    cp -pf $so $so.new
    mv $so.new  $CCCDIR/usr/lib/$CCCBIN/`basename $so`
done


( cd ssl && m )
