#!/bin/sh

date=`date -u '+%a, %d %b %Y %H:%M:%S %Z'`

cat << EOF
Content-type: text/plain;charset=UTF-8
Expires: $date

CGI printenv

EOF

echo 'Date:'
date
echo

echo 'Id:'
id
echo

echo 'Env:'
printenv
echo

echo -n 'INPUT: '
dd  2>/dev/null
