#!/bin/bash
#nyúzó
rm log*

touch sema  # ennek letörlésével lehet az öszeset leállítani

HOST=localhost
PORT=45001
SSL=ssl

c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &

c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &
c-test1.exe $HOST $PORT $SSL  &

