#!/bin/bash

compile()
{
    ( cd  driver-sqlite3    && m )
    ( cd  driver-postgres   && m )
    ( cd  driver-oracle     && m )
    ( cd  driver-mysql      && m )
    ( cd  driver-db2        && m )
    ( cd  util              && m )
   #( cd  test              && m )
}

compile # 2>&1 | tee log-install

