#!/bin/bash

. t--host

export SSLFORW_CAPATH=
export SSLFORW_CAFILE=

export SSLFORW_PKEYFILE=pem/clnpkey/demo.pem
export SSLFORW_CERTFILE=pem/clnpkey/demo.pem


sslforw-term.exe  $host:40003  terminal-xft.exe

