#!/bin/bash

PORT=46000
APPL=test-changeitem.py

# 1) egyszerű listener ssl nélkül
# jtlisten.exe $PORT $APPL -jtdebug


# 2) egyszerű listener ssl forwardinggal (kell hozzá a server.pem fil?)
# jtlisten.exe $PORT sslforward.exe $APPL -jtdebug


# 3) Önálló program indítás 
 $APPL -jtauto -jtdebug


# 4) sokszori indítás jtstart-tal
# előzör jtstart.exe-t indítjuk,
# ebben csak egy gomb van, ami indítja a paraméterként kapott programot,
# ennek az az értelme, hogy nem kell várni a Jáva betöltődésére,
# miközben a tesztelt alkalmazást fordítgatjuk
# jtstart.exe "$APPL"  &
 