#!/bin/bash
c++app.sh  @parfile.bld
terminal-icon.exe

convert terminal.svg terminal.ico
convert terminal.svg terminal.xpm

cp  terminal.svg ${CCCDIR}/usr/bin
cp  terminal.xpm ${CCCDIR}/usr/bin
cp  terminal.ico ${CCCDIR}/usr/bin
