#!/bin/bash
export BUILD_LIBDIR=${CCCDIR}/usr/lib/${CCCBIN}

# dbaseiii.so behuzza a fullscreen konyvtarakat
# ha az nem megfelelo, akkor dbaseiii.lib-et kell linkelni;
# a memokezeleshez linkelni kell a btbtx tablaobjektumot

bapp_unix0.b -sccc${CCCVER}_dbaseiii

