#!/bin/bash

echo >log1

echo '
---------------------------------------------------------------
demo0: felépíti, majd kiírja az egész dokumentum objektumot
---------------------------------------------------------------' >>log1
demo0.exe example1.xml >>log1


echo '
---------------------------------------------------------------
demo1: megszámlálja az különféle típusú elemeket
---------------------------------------------------------------' >>log1
demo1.exe example1.xml >>log1


echo '
---------------------------------------------------------------
demo2: kilistázza az ügyfeleket
---------------------------------------------------------------' >>log1
demo2.exe example1.xml >>log1


echo '
---------------------------------------------------------------
demo3: kilistázza az számlákat
---------------------------------------------------------------' >>log1
demo3.exe example1.xml >>log1


 
z log

