#!/bin/bash

echo >log1

echo '
---------------------------------------------------------------
demo0: felépíti, majd kiírja az egész dokumentum objektumot
---------------------------------------------------------------' >>log2
demo0.exe example2.xml >>log2


echo '
---------------------------------------------------------------
demo1: megszámlálja az különféle típusú elemeket
---------------------------------------------------------------' >>log2
demo1.exe example2.xml >>log2


echo '
---------------------------------------------------------------
demo2: kilistázza az ügyfeleket
---------------------------------------------------------------' >>log2
demo2.exe example2.xml >>log2


echo '
---------------------------------------------------------------
demo3: kilistázza az számlákat
---------------------------------------------------------------' >>log2
demo3.exe example2.xml >>log2


 
z log2

