#!/bin/bash
# set -x

bapp_unix_.b   @parfile.bld

cp -pf obj$CCCBIN/*.lib $CCCDIR/usr/lib/$CCCBIN
cp -pf *.ch  $CCCDIR/usr/include

#so közvetlen cp helyett mv-vel kerül a helyére,
#hogy az éppen futó programok nem szálljanak el
find obj$CCCBIN/*.so | while read so; do
    cp -pf $so $so.new
    mv $so.new  $CCCDIR/usr/lib/$CCCBIN/`basename $so`
done
