#!/bin/bash
#set -x

if ! test -f jterminal.jar; then
    javac -version 

    if javac -cp . -encoding UTF-8 -nowarn jterminal.java 2>log-jterminal; then
        mkjar
        cat log-jterminal
    else
        tv.exe log-jterminal &
        exit 1
    fi
fi

cp jterminal.jar ~/bin

