#!/bin/bash


OPT=""
OPT+=" -c"
OPT+=" -O0"
OPT+=" -DMINGW" 
OPT+=" -D_CCC_"
OPT+=" -D_CCC3_"
OPT+=" -DWIN32"
OPT+=" -DWINDOWS"
OPT+=" -DMULTITHREAD"
OPT+=" -funsigned-char"
OPT+=" -mms-bitfields"
OPT+=" -Wno-unused"
OPT+=" -Wno-unused-value"
OPT+=" -Wno-trigraphs"
OPT+=" -Wno-empty-body"
OPT+=" -Wno-int-to-pointer-cast"
OPT+=" -Wno-incompatible-ms-struct"
OPT+=" -Wno-unknown-warning-option"
OPT+=" -I ."
OPT+=" -I ${CCCDIR}/usr/include"
OPT+=" -I ${CCCDIR}/ccclib/src/include"

#set -x


compile()
{
    name="${1##*/}                   "
    echo -n SETUP: "${name:0:24}"
    sum=$(cat $0 $1 | sha256sum) # sscript+source -> sha256sum
    sum=setup-${sum:0:64}
    if [ -f $BUILD_CACHE/$sum ]; then
        cp  $BUILD_CACHE/$sum ${name//.cpp/.o}
        echo " cached"
    elif c++ ${OPT} $1; then
        if [ -d "$BUILD_CACHE" ]; then
            cp ${name//.cpp/.o} $BUILD_CACHE/$sum
        fi
        echo " ok"
    else
        echo " FAILED"
    fi
}

if [ "$1" == "" ]; then
    #cc-all
    for FILE in *.cpp; do
        if ! [ -f ${FILE//.cpp/.o} ];then
            compile $FILE
        fi
    done
else
    #cc-one
    BASE=${1##*/}
    if ! [ -f ${BASE//.cpp/.o} ];then
        compile "$1"
    fi
fi


