#!/bin/bash

#set -x

export BUILD=${CCCDIR}/usr/bin/build.exe
export PRG2PPO=${CCCDIR}/usr/bin/prg2ppo.exe
export CCOMP=${CCCDIR}/usr/bin/ccomp.exe
export REMOVECR=${CCCDIR}/usr/bin/removecr.exe

flag=""

if  ! test -x ${BUILD}; then
    #echo compile: ${BUILD}
    flag+="B"
fi

if  ! test -x ${PRG2PPO}; then
    #echo compile: ${PRG2PPO}
    flag+="P"
fi

if  ! test -x ${CCOMP}; then
    #echo compile: ${CCOMP}
    flag+="C"
fi

if  ! test -x ${REMOVECR}; then
    #echo compile: ${REMOVECR}
    flag+="R"
fi

#echo ${flag}

if [[ ${flag} != "" ]]; then

    make_setup_lib

    ( cd build      &&  ../cc && ../xx )
    ( cd ccomp      &&  ../cc && ../xx )
    ( cd removecr   &&  ../cc && ../xx )
    ( cd prg2ppo    &&  ../cc && ../xx )

    #cat build/log-link           >log-install
    #cat ccomp/log-link          >>log-install
    #cat prg2ppo/log-link        >>log-install
    #less log-install
fi


