#!/bin/bash

./cc ${CCCDIR}/ccclib/src/ui_/main.cpp
./cc ${CCCDIR}/ccclib/src/ui_/remoteio.cpp

./cc ${CCCDIR}/ccclib/src/windows/envir.cpp
./cc ${CCCDIR}/ccclib/src/windows/filecopy.cpp
./cc ${CCCDIR}/ccclib/src/windows/filecreat.cpp
./cc ${CCCDIR}/ccclib/src/windows/findnext.cpp
./cc ${CCCDIR}/ccclib/src/windows/fseek.cpp
./cc ${CCCDIR}/ccclib/src/windows/lstat.cpp
./cc ${CCCDIR}/ccclib/src/windows/nlstext.cpp
./cc ${CCCDIR}/ccclib/src/windows/signals.cpp
./cc ${CCCDIR}/ccclib/src/windows/spawn.cpp

./cc ${CCCDIR}/ccclib/src/add.cpp
./cc ${CCCDIR}/ccclib/src/argv.cpp
./cc ${CCCDIR}/ccclib/src/array.cpp
./cc ${CCCDIR}/ccclib/src/asc.cpp
./cc ${CCCDIR}/ccclib/src/asort.cpp
./cc ${CCCDIR}/ccclib/src/at.cpp
./cc ${CCCDIR}/ccclib/src/binary.cpp
./cc ${CCCDIR}/ccclib/src/bit.cpp
./cc ${CCCDIR}/ccclib/src/break.cpp
./cc ${CCCDIR}/ccclib/src/color.cpp
./cc ${CCCDIR}/ccclib/src/direct.cpp
./cc ${CCCDIR}/ccclib/src/dirsep.cpp
./cc ${CCCDIR}/ccclib/src/dtos.cpp
./cc ${CCCDIR}/ccclib/src/empty.cpp
./cc ${CCCDIR}/ccclib/src/equalto.cpp
./cc ${CCCDIR}/ccclib/src/errorcode.cpp
./cc ${CCCDIR}/ccclib/src/errorgen.cpp
./cc ${CCCDIR}/ccclib/src/eval.cpp
./cc ${CCCDIR}/ccclib/src/evalarr.cpp
./cc ${CCCDIR}/ccclib/src/exec.cpp
./cc ${CCCDIR}/ccclib/src/file.cpp
./cc ${CCCDIR}/ccclib/src/fileconv.cpp
./cc ${CCCDIR}/ccclib/src/fileio.cpp
./cc ${CCCDIR}/ccclib/src/hashcode.cpp
./cc ${CCCDIR}/ccclib/src/i2bin.cpp
./cc ${CCCDIR}/ccclib/src/isalpha.cpp
./cc ${CCCDIR}/ccclib/src/max.cpp
./cc ${CCCDIR}/ccclib/src/object.cpp
./cc ${CCCDIR}/ccclib/src/pad.cpp
./cc ${CCCDIR}/ccclib/src/procline.cpp
./cc ${CCCDIR}/ccclib/src/push.cpp
./cc ${CCCDIR}/ccclib/src/pushcall.cpp
./cc ${CCCDIR}/ccclib/src/qout.cpp
./cc ${CCCDIR}/ccclib/src/quit.cpp
./cc ${CCCDIR}/ccclib/src/rat.cpp
./cc ${CCCDIR}/ccclib/src/replicate.cpp
./cc ${CCCDIR}/ccclib/src/round.cpp
./cc ${CCCDIR}/ccclib/src/run.cpp
./cc ${CCCDIR}/ccclib/src/slice.cpp
./cc ${CCCDIR}/ccclib/src/ss.cpp
./cc ${CCCDIR}/ccclib/src/stat.cpp
./cc ${CCCDIR}/ccclib/src/stdcmp.cpp
./cc ${CCCDIR}/ccclib/src/str.cpp
./cc ${CCCDIR}/ccclib/src/str2bin.cpp
./cc ${CCCDIR}/ccclib/src/string.cpp
./cc ${CCCDIR}/ccclib/src/stuff.cpp
./cc ${CCCDIR}/ccclib/src/stvar.cpp
./cc ${CCCDIR}/ccclib/src/substr.cpp
./cc ${CCCDIR}/ccclib/src/thread.cpp
./cc ${CCCDIR}/ccclib/src/time.cpp
./cc ${CCCDIR}/ccclib/src/transform.cpp
./cc ${CCCDIR}/ccclib/src/trim.cpp
./cc ${CCCDIR}/ccclib/src/upper.cpp
./cc ${CCCDIR}/ccclib/src/utf8conv.cpp
./cc ${CCCDIR}/ccclib/src/val.cpp
./cc ${CCCDIR}/ccclib/src/valtype.cpp
./cc ${CCCDIR}/ccclib/src/variable.cpp
./cc ${CCCDIR}/ccclib/src/variablex.cpp
./cc ${CCCDIR}/ccclib/src/varprint.cpp
./cc ${CCCDIR}/ccclib/src/xmethod3.cpp
./cc ${CCCDIR}/ccclib/src/xmethod6.cpp

## plusz le kell forditani a helyben megorzott cpp-ket,
## amik a ccc es ccc_ui_ konyvtarak forditasakor keszultek prg-bol 
## (ez egyszerre mindent lefordit)

./cc 
