#!/bin/bash
#export CCC_STRING_TAB=STRTAB

c++app.sh @par-unix.bld  
c++app.sh @par-unixui.bld  
 
( cd utility && m )
#( cd utility/btpasswd && m )
#( cd utility/btpasswd_windll && m )
( cd utility/dbf2bt && m )
 