#define QMRPAR                          1
#define LPAR                            2
#define SLRPAR                          3
#define RPAR                            4
#define SLASH                           5
#define SYMBOL                          6
#define TEXT                            7
#define CDATA                           8
#define LPARQM                          9
#define EQ                             10
#define STRING                         11
