#define ROOT                            1
#define LPARQM                          2
#define QMRPAR                          3
#define LPAR                            4
#define SLRPAR                          5
#define RPAR                            6
#define SLASH                           7
#define SYMBOL                          8
#define TEXT                            9
#define CDATA                          10
#define EQ                             11
#define STRING                         12
