#!/bin/bash

if [ "$1" == "-x" ]; then
    rm -f $CCCDIR/usr/bin/$CCCUNAME/build.exe
    rm -f $CCCDIR/usr/bin/$CCCUNAME/ppo2cpp.exe
    rm -f $CCCDIR/usr/bin/$CCCUNAME/prg2ppo.exe
    rm -f $CCCDIR/usr/bin/$CCCUNAME/removecr.exe
fi

rm -f $CCCDIR/usr/lib/$CCCBIN/setup.lib

cleandir()
{
    pushd $1
    rm -f *.o *.bak compopt outcpp rsplink
    popd
}

cleandir .
cleandir build
cleandir buildp
cleandir ppo2cpp
cleandir prg2ppo
cleandir removecr
