#!/bin/bash
#set -x

mkexe()
{
    if [ ! -x $CCCDIR/usr/bin/$CCCUNAME/$1.exe ]; then
        make.b lib setup
        echo "compiling $1 for setup"
        pushd $1 >/dev/null; m; popd >/dev/null
    fi
}

mkexe build
mkexe prg2ppo
mkexe removecr
 