#!/bin/bash

#set -x

update()
{
    :
    echo $1 $2 $3
    
    cat $1 | sed "s/$2/$3/g"  >tmp
    mv tmp  $1
    chmod +x $1
}



find . | while read fspec; do
    base=${fspec##*/}

    if [ ${base:0:1} == m  ]; then

        if grep bapp_unix0.b $fspec >/dev/null; then
           update    $fspec  bapp_unix0.b c++app.sh
        fi

        if grep bapp_unix_.b $fspec >/dev/null; then
           update    $fspec   bapp_unix_.b cccapp.sh
        fi

        if grep bapp_unixc.b $fspec >/dev/null; then
           update    $fspec   bapp_unixc.b cccapp_term.sh
        fi
    fi
done