#!/bin/bash
#set -x
#echo `pwd`

bapp_unix0.b  -d. -dunix  -sccc3_sslsocket  -bssl

cp -pf obj$CCCBIN/*.lib  $CCCDIR/usr/lib/$CCCBIN
cp -pf obj$CCCBIN/*.so  $CCCDIR/usr/lib/$CCCBIN
cp -pf ssl.ch  $CCCDIR/usr/include
