#!/bin/bash

#csak akkor tudja importálni a localhost-tal aláírt test-et,
#ha előzőleg a localhost is importálva volt,
#később a localhost-ot lehet törölni

keytool -import \
     -keystore keys  -storepass changeit \
     -alias test -file test-cert.pem


keytool -list -v -keystore keys -storepass changeit | less
 