#!/bin/bash


if [ "$CCCVER" == "2"  ];then
    :;#ok
elif [ "$CCCVER" == "3"  ];then
    :;#ok
elif test -f $CCCDIR/usr/lib/$CCCBIN/ccc2.lib; then
    export CCCVER=2
elif test -f $CCCDIR/usr/lib/$CCCBIN/ccc3.lib; then
    export CCCVER=3
else
    echo Cannot detect CCC version.
    exit 1
fi

bapp_unix0.b @parfilex.bld

