#line 2 "ppo/input.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else        /* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif       /* __STDC__ */
#endif       /* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *   if ( condition_holds )
 *           yyless( 5 );
 *   else
 *           do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
     do \
             { \
             /* Undo effects of setting up yytext. */ \
             *yy_cp = yy_hold_char; \
             YY_RESTORE_YY_MORE_OFFSET \
             yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
             YY_DO_BEFORE_ACTION; /* set up yytext again */ \
             } \
     while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
     {
     FILE *yy_input_file;

     char *yy_ch_buf;                /* input buffer */
     char *yy_buf_pos;               /* current position in input buffer */

     /* Size of input buffer in bytes, not including room for EOB
      * characters.
      */
     yy_size_t yy_buf_size;

     /* Number of characters read into yy_ch_buf, not including EOB
      * characters.
      */
     int yy_n_chars;

     /* Whether we "own" the buffer - i.e., we know we created it,
      * and can realloc() it to grow it, and should free() it to
      * delete it.
      */
     int yy_is_our_buffer;

     /* Whether this is an "interactive" input source; if so, and
      * if we're using stdio for input, then we want to use getc()
      * instead of fread(), to make sure we stop fetching input after
      * each newline.
      */
     int yy_is_interactive;

     /* Whether we're considered to be at the beginning of a line.
      * If so, '^' rules will be active on the next match, otherwise
      * not.
      */
     int yy_at_bol;

     /* Whether to try to fill the input buffer when we reach the
      * end of it.
      */
     int yy_fill_buffer;

     int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
     /* When an EOF's been seen but there's still some text to process
      * then we mark the buffer as YY_EOF_PENDING, to indicate that we
      * shouldn't try reading from the input source any more.  We might
      * still have a bunch of tokens to match, though, because of
      * possible backing-up.
      *
      * When we actually see the EOF, we change the status to "new"
      * (via yyrestart()), so that the user can continue scanning by
      * just pointing yyin at a new input file.
      */
#define YY_BUFFER_EOF_PENDING 2
     };

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;               /* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;              /* whether we need to initialize */
static int yy_start = 0;     /* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
     { \
     if ( ! yy_current_buffer ) \
             yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
     yy_current_buffer->yy_is_interactive = is_interactive; \
     }

#define yy_set_bol(at_bol) \
     { \
     if ( ! yy_current_buffer ) \
             yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
     yy_current_buffer->yy_at_bol = at_bol; \
     }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
     yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
     yy_hold_char = *yy_cp; \
     *yy_cp = '\0'; \
     yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_acclist[142] =
    {   0,
       29,   29,   65,   28,   64,   27,   64,   28,   64,   28,
       64,   28,   64,   23,   28,   64,   28,   64,   28,   64,
       28,   64,   28,   64,   35,   64,   32,   35,   64,   35,
       64,   35,   64,   39,   64,   36,   39,   64,   39,   64,
       43,   64,   40,   43,   64,   43,   64,   47,   64,   44,
       47,   64,   47,   64,   51,   64,   48,   51,   64,   51,
       64,   63,   64,   62,   64,   63,   64,   63,   64,   63,
       64,   63,   64,   63,   64,   63,   64,   63,   64,   63,
       64,   29,   64,   64,    4,   64,    3,   64,    4,   64,
        7,   64,    6,   64,    7,   64,   26,   25,   22,   21,

       37,   41,   58,   60,   29,   30,   30,   31,   24,   33,
       59,   38,   42,   45,   49,    1,   13,   11,   34,   61,
       52,   56,    2,    5,   14,    9,   12,   20,   46,   50,
       53,   54,   57,   15,   10,   55,   19,    8,   18,   17,
       16
    } ;

static yyconst short int yy_accept[276] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    3,
        3,    3,    3,    4,    6,    8,   10,   12,   14,   17,
       19,   21,   23,   25,   27,   30,   32,   34,   36,   39,
       41,   43,   46,   48,   50,   53,   55,   57,   60,   62,
       64,   66,   68,   70,   72,   74,   76,   78,   80,   82,
       84,   85,   87,   89,   91,   93,   95,   97,   97,   98,
       98,   99,   99,   99,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  101,  101,
      101,  101,  101,  102,  102,  102,  102,  103,  103,  103,

      103,  103,  103,  103,  103,  104,  104,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  106,  107,  108,
      109,  109,  109,  109,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  113,  113,  113,  113,  114,
      114,  114,  114,  115,  115,  115,  115,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,

      116,  117,  117,  117,  118,  118,  118,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  120,  120,  120,  120,
      120,  120,  120,  121,  122,  122,  122,  123,  123,  123,
      124,  125,  125,  125,  126,  127,  127,  128,  128,  128,
      129,  129,  129,  129,  130,  130,  130,  130,  131,  131,
      131,  132,  133,  133,  134,  134,  135,  136,  136,  136,
      136,  136,  137,  138,  139,  139,  139,  139,  139,  140,
      140,  141,  141,  142,  142
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    1,
        1,    7,    1,    1,    1,    1,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,   10,   11,
        1,   12,    1,    1,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,    1,    1,    1,   13,    1,   14,   13,   15,   16,

       17,   18,   13,   13,   19,   13,   13,   20,   21,   22,
       23,   13,   24,   25,   26,   27,   28,   13,   13,   29,
       13,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[30] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    5,    6,    1,
        1,    7,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8
    } ;

static yyconst short int yy_base[320] =
    {   0,
        0,   10,    3,   20,   26,    0,   55,    0,   84,    0,
      113,    0,  140,  150,  145,  155,  696,  695,  156,  159,
      160,  161,  701,  704,  704,  696,  693,  158,  166,  687,
      171,  164,  694,  704,  704,  692,  689,  704,  704,  182,
      704,  704,  186,  704,  704,  692,  704,  704,  691,  704,
      704,  688,  685,  179,  679,  193,    6,  194,  158,    0,
      193,  704,  704,  678,  704,  704,  677,  683,  704,  680,
      704,  682,  200,  704,  197,    0,  204,    0,  681,  660,
      665,  190,  127,  656,  658,  192,  676,  704,  674,  212,
      671,  214,  704,  216,  223,  225,  704,  222,  232,  674,

      673,  672,  671,  668,  704,  665,  704,  667,    0,  216,
      219,  217,  651,  239,  226,  646,    0,  704,  239,  704,
        0,    0,  664,  704,  659,  662,  652,  642,  644,  635,
      644,  232,  644,  644,  641,  633,  630,  248,  704,  245,
      252,  651,  254,  650,  260,  262,  649,  704,  639,  624,
      633,  250,  636,  635,  639,  637,  641,  631,  630,  620,
      621,  622,  619,  620,  612,  257,  615,  612,  616,  611,
      617,  268,  627,  273,  704,  274,  626,  276,  704,  278,
      625,  282,  704,  280,  289,  291,  704,  288,  298,  615,
      614,  608,  605,  606,  598,  286,  551,  548,  544,  541,

      704,  488,  468,  704,  471,  470,  704,  470,  462,  455,
      456,  463,  459,  457,  301,  704,  302,  454,  304,  445,
      306,  437,  704,  704,  418,  416,  704,  416,  408,  704,
      704,  407,  410,  704,  704,  408,  704,  409,  402,  704,
      405,  389,  309,  704,  311,  409,  314,  704,  312,  401,
      704,  704,  378,  704,  364,  704,  704,  355,  304,  276,
      269,  704,  704,  704,  251,  253,  246,  241,  704,  215,
      704,  215,  704,  704,  321,  329,  337,  345,  353,  361,
      369,  377,  385,  393,  401,  408,  415,  422,  429,  437,
      445,  453,  461,  469,  205,  476,  483,  491,  189,  174,

       11,  499,  507,  510,  518,  526,  534,  542,  549,  556,
      559,  562,  565,  573,  581,  589,  597,  605,  613
    } ;

static yyconst short int yy_def[320] =
    {   0,
      275,  275,  276,  276,  274,    5,  274,    7,  274,    9,
      274,   11,  277,  277,   14,   14,  278,  278,  279,  279,
      280,  280,  274,  274,  274,  281,  282,  274,  274,  274,
      274,  274,  283,  274,  274,  284,  285,  274,  274,  286,
      274,  274,  287,  274,  274,  288,  274,  274,  289,  274,
      274,  290,  291,  274,  274,  274,  274,  274,  274,  292,
      293,  274,  274,  274,  274,  274,  274,  281,  274,  282,
      274,  294,  274,  274,  274,  295,  274,   32,  283,  274,
      274,  274,  274,  274,  274,  274,  283,  274,  284,  274,
      285,  274,  274,  274,  286,  274,  274,  274,  287,  296,

      288,  297,  289,  290,  274,  291,  274,  298,  299,  274,
      274,  274,  274,  274,  274,  274,  292,  274,  293,  274,
      300,  301,  294,  274,  302,  303,  304,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      305,  306,  307,  308,  309,  310,  298,  274,  311,  274,
      274,  274,  312,  313,  302,  302,  303,  304,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  314,  315,  305,  274,  305,  306,  307,  274,  307,
      308,  274,  274,  274,  309,  274,  274,  274,  310,  311,
      274,  274,  274,  274,  274,  274,  312,  274,  313,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  314,  274,  314,  315,  316,  317,
      318,  319,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  316,  274,  316,  317,  318,  274,  318,  319,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,    0,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274
    } ;

static yyconst short int yy_nxt[734] =
    {   0,
      274,  274,   25,   26,   35,   27,   36,   28,   37,   29,
       30,   31,   25,   26,   32,   27,   33,   28,  154,   29,
       30,   35,  112,   36,  113,   37,   38,   39,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   41,   42,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   44,   45,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   47,   48,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   51,   52,  132,   53,   50,   54,  133,   50,
       55,   56,   51,   52,   57,   53,   58,   54,   63,   59,
       55,   63,   66,   66,   71,   72,   64,   73,   74,   64,
       67,   67,   77,   75,  116,   78,  113,   79,   80,   81,
       82,  153,   83,   92,   93,  107,  108,   96,   97,   94,
       84,   85,   86,   98,  110,  114,  149,  111,  115,  119,

      120,   73,   74,  125,  126,   77,  136,   75,   78,  130,
       79,  131,  127,  138,  139,   92,   93,  110,  137,  140,
      111,   94,  141,  142,   92,   93,   96,   97,  143,  144,
       94,  273,   98,   96,   97,  112,  150,  113,  151,   98,
      114,  272,  116,  115,  113,  119,  120,  164,  165,  138,
      139,  172,  173,  166,  175,  140,  179,  271,  176,  270,
      180,  182,  183,  186,  187,  194,  195,  184,  269,  188,
      216,  196,  208,  209,  217,  175,  175,  268,  179,  176,
      179,   92,  180,  182,  183,   96,  219,  220,  267,  184,
      182,  183,  186,  187,  221,  222,  184,  266,  188,  186,

      187,  228,  229,  216,  216,  188,  244,  217,  248,  138,
      245,  244,  249,  244,  248,  245,  248,  265,  182,  186,
      249,   24,   24,   24,   24,   24,   24,   24,   24,   34,
       34,   34,   34,   34,   34,   34,   34,   50,   50,   50,
       50,   50,   50,   50,   50,   60,   60,   60,   60,   60,
       60,   60,   60,   62,   62,   62,   62,   62,   62,   62,
       62,   65,   65,   65,   65,   65,   65,   65,   65,   68,
       68,  264,   68,   68,   68,   68,   68,   70,   70,  263,
       70,   70,   70,   70,   70,   87,   87,   87,   87,   87,
       87,   87,   87,   89,   89,  262,   89,   89,   89,   89,

       89,   91,   91,  187,   91,   91,   91,   91,   91,   95,
       95,  183,   95,   95,  261,   95,   99,   99,  260,   99,
       99,  259,   99,  101,  258,  257,  256,  101,  255,  101,
      103,  254,  253,  252,  103,  251,  103,  104,  104,  187,
      104,  104,  104,  104,  104,  106,  106,  183,  106,  106,
      106,  106,  106,  117,  117,  117,  139,  117,  117,  117,
      117,  118,  118,  118,  118,  118,  118,  118,  118,  123,
      123,  123,  123,  123,  123,  123,  123,  145,  242,  241,
      240,  239,  238,  145,  146,  237,  236,  235,  234,  233,
      146,  147,  147,  147,  147,  147,  147,  147,  147,  155,

      155,  232,  155,  155,  155,  155,  155,  157,  157,  157,
      157,  157,  157,  157,  157,  158,  158,  158,  174,  174,
      174,  174,  174,  174,  174,  174,  177,  177,  177,  177,
      177,  177,  177,  177,  178,  178,  178,  178,  178,  178,
      178,  178,  181,  181,  181,  181,  181,  181,  181,  181,
      185,  185,  231,  185,  185,  200,  185,  189,  189,  230,
      189,  189,  198,  189,  190,  190,  190,  197,  197,  197,
      199,  199,  199,  215,  215,  215,  215,  215,  215,  215,
      215,  218,  218,  218,  218,  218,  218,  218,  218,  243,
      243,  243,  243,  243,  243,  243,  243,  246,  246,  246,

      246,  246,  246,  246,  246,  247,  247,  247,  247,  247,
      247,  247,  247,  250,  250,  250,  250,  250,  250,  250,
      250,  227,  226,  225,  224,  223,  191,   97,   93,  139,
      214,  213,  212,  211,  210,  207,  206,  205,  204,  203,
      202,  201,  159,   74,   73,  156,  200,  198,  193,  192,
      191,  148,   97,   93,  171,  170,  169,  168,  167,  163,
      162,  161,  160,  159,   74,  156,  124,  151,  152,  148,
      105,  105,  102,  102,  100,  100,   90,   90,   88,  135,
      134,  129,  128,   88,  124,   69,   69,  122,  121,  109,
      105,  105,  102,  100,   90,   90,   88,   76,   69,   69,

      274,   61,   61,   23,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274
    } ;

static yyconst short int yy_chk[734] =
    {   0,
        0,    0,    1,    1,    3,    1,    3,    1,    3,    1,
        1,    2,    2,    2,    2,    2,    2,    2,  301,    2,
        2,    4,   57,    4,   57,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   13,   13,   83,   13,   15,   13,   83,   15,
       13,   14,   14,   14,   14,   14,   16,   14,   19,   16,
       14,   20,   21,   22,   28,   28,   19,   29,   29,   20,
       21,   22,   31,   29,   59,   31,   59,   31,   32,   32,
       32,  300,   32,   40,   40,   54,   54,   43,   43,   40,
       32,   32,   32,   43,   56,   58,  299,   56,   58,   61,

       61,   73,   73,   75,   75,   77,   86,   73,   77,   82,
       77,   82,  295,   90,   90,   92,   92,  110,   86,   90,
      110,   92,   94,   94,   95,   95,   96,   96,   98,   98,
       95,  272,   96,   99,   99,  111,  112,  111,  112,   99,
      114,  270,  115,  114,  115,  119,  119,  132,  132,  138,
      138,  140,  140,  132,  141,  138,  143,  268,  141,  267,
      143,  145,  145,  146,  146,  152,  152,  145,  266,  146,
      172,  152,  166,  166,  172,  174,  176,  265,  178,  174,
      180,  176,  178,  182,  182,  180,  184,  184,  261,  182,
      185,  185,  186,  186,  188,  188,  185,  260,  186,  189,

      189,  196,  196,  215,  217,  189,  219,  215,  221,  217,
      219,  243,  221,  245,  249,  243,  247,  259,  245,  249,
      247,  275,  275,  275,  275,  275,  275,  275,  275,  276,
      276,  276,  276,  276,  276,  276,  276,  277,  277,  277,
      277,  277,  277,  277,  277,  278,  278,  278,  278,  278,
      278,  278,  278,  279,  279,  279,  279,  279,  279,  279,
      279,  280,  280,  280,  280,  280,  280,  280,  280,  281,
      281,  258,  281,  281,  281,  281,  281,  282,  282,  255,
      282,  282,  282,  282,  282,  283,  283,  283,  283,  283,
      283,  283,  283,  284,  284,  253,  284,  284,  284,  284,

      284,  285,  285,  250,  285,  285,  285,  285,  285,  286,
      286,  246,  286,  286,  242,  286,  287,  287,  241,  287,
      287,  239,  287,  288,  238,  236,  233,  288,  232,  288,
      289,  229,  228,  226,  289,  225,  289,  290,  290,  222,
      290,  290,  290,  290,  290,  291,  291,  220,  291,  291,
      291,  291,  291,  292,  292,  292,  218,  292,  292,  292,
      292,  293,  293,  293,  293,  293,  293,  293,  293,  294,
      294,  294,  294,  294,  294,  294,  294,  296,  214,  213,
      212,  211,  210,  296,  297,  209,  208,  206,  205,  203,
      297,  298,  298,  298,  298,  298,  298,  298,  298,  302,

      302,  202,  302,  302,  302,  302,  302,  303,  303,  303,
      303,  303,  303,  303,  303,  304,  304,  304,  305,  305,
      305,  305,  305,  305,  305,  305,  306,  306,  306,  306,
      306,  306,  306,  306,  307,  307,  307,  307,  307,  307,
      307,  307,  308,  308,  308,  308,  308,  308,  308,  308,
      309,  309,  200,  309,  309,  199,  309,  310,  310,  198,
      310,  310,  197,  310,  311,  311,  311,  312,  312,  312,
      313,  313,  313,  314,  314,  314,  314,  314,  314,  314,
      314,  315,  315,  315,  315,  315,  315,  315,  315,  316,
      316,  316,  316,  316,  316,  316,  316,  317,  317,  317,

      317,  317,  317,  317,  317,  318,  318,  318,  318,  318,
      318,  318,  318,  319,  319,  319,  319,  319,  319,  319,
      319,  195,  194,  193,  192,  191,  190,  181,  177,  173,
      171,  170,  169,  168,  167,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,  151,  150,
      149,  147,  144,  142,  137,  136,  135,  134,  133,  131,
      130,  129,  128,  127,  126,  125,  123,  116,  113,  108,
      106,  104,  103,  102,  101,  100,   91,   89,   87,   85,
       84,   81,   80,   79,   72,   70,   68,   67,   64,   55,
       53,   52,   49,   46,   37,   36,   33,   30,   27,   26,

       23,   18,   17,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./input.lex"
#define INITIAL 0
/*
 *  CCC - The Clipper to C++ Compiler
 *  Copyright (C) 2005 ComFirm BT.
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
#define st_incl 1
#define st_ifdef 2
#define st_ifndef 3
#define st_ifeq 4
#define st_ifneq 5
 
#define st_waitelse 6
#define st_waitendif 7
#define st_comment 8
 
#define st_raw 9
#define st_waitraw 10

#line 26 "./input.lex"

//Ez a flex program vezérli az input olvasását
//
//  végzi az inkludálást,
//  kihagyja az ifdef/else/endif kihagyandó részeit,
//  kihagyja a kommenteket,
//  kiegyenesíti a folytatósorokat,
//  szétválasztja az egy sorba írt utasításokat,
//  számolja a sorokat,
//  kikerüli a stringeket.

//Figyelem:
//  A "st_comment" név helyett nem jó az egyszerű "comment",
//  mert a Windowson include filékben (msxml.h) zavart okoz 
//  a Flex által generált '#define comment 8' makró.
 

#include <string.h>
#include <cccapi.h>

//a generalt kodban:
//#define ECHO (void) fwrite( yytext, yyleng, 1, yyout ) 
//gcc 4.3.2 warning: ignoring return value
//#define ECHO (0==fwrite(yytext,yyleng,1,yyout))

//Bizonyos esetekben (folytatósor, sorelválasztó ;)
//a generált kimeneten CR jelenhet meg, ami a további
//fordítást elrontja, ezért legegyszerűbb, ha a CR
//karaktereket, már a bemenet olvasásakor eldobjuk.
//Ugyancsak el kell dobni a filék végén lévő esetleges 
//eof (chr(26)) karaktert, amit a UNIX nem fogad el.



#define YY_INPUT(buf,result,max_size)  yy_input(buf,&result,max_size)

static char *reproctxt=0;
static int   reproclen=0;
static int   reprocidx=0;
 
int yy_input(char *buf, int *result, int max_size)
{
    if( reproctxt!=0 )
    {
        int c=26;

        while( (reprocidx<reproclen) && ((c=='\r') || (c==26))  )
        {
            c=reproctxt[reprocidx++];
        }
        if( reprocidx>=reproclen )
        {
            free(reproctxt);
            reproctxt=0;
            reproclen=0;
            reprocidx=0;
        }
        if( c=='\n' )
        {
            --yylineno;
        }
        if( (c!='\r') && (c!=26) )
        {
            buf[0]=c;
            *result=1;
            return *result;
        }
    }

    int c=getc(yyin);
    
    while( (c=='\r') || (c==26) )
    {
        c=getc(yyin);
    }

    if( c!=EOF )
    {
        buf[0]=c;
        *result=1;
    }
    else
    {
        *result=YY_NULL;
    }
    
    //printf("%c",c);
    return *result;
}
 

 
#define YY_NEVER_INTERACTIVE     1

#define MAX_INCLUDE_DEPTH       10
#define MAX_LINE_SIZE         8192
#define MAX_STATE_DEPTH         20
 
static YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
static unsigned lnumber_stack[MAX_INCLUDE_DEPTH]; 
static char *fname_stack[MAX_INCLUDE_DEPTH]; 
static int include_stack_ptr=0;
static int include_changed=0;
 
static int state_stack[MAX_STATE_DEPTH];
static int state_stack_ptr=0;

static char *outbuf=0;
static int  outbuf_idx=0;
static int  outbuf_siz=0;
static int  outlineno=0;
static int  outtype=0;

static char *filein;

extern void error(const char*);
static void procinclude(void);
static void procifdef(int type);
static void statepush(int state);
static void statepop(void);
static char *getfilename();
static char *tabular(int p);
static void outchar(int c);
static void outtrim();
static void outstr(const char *s);
static int  outempty(void);
static void printbuf(void);
static void counter(void);

extern void _clp_nextline(int argno);
extern void _clp_prepro(int argno);
extern void _clp_define(int argno);
extern void _clp_undef(int argno);
extern void _clp_translate(int argno);
extern void _clp_searchdefine(int argno);
extern void _clp_searchinclude(int argno);


static int ifdef_level=0;
static void assert_else()
{
    if( ifdef_level<=0 )
        error("#else directive without #if");
}
static void assert_endif()
{
    if( ifdef_level<0 )
        error("#endif directive without #if");
}
static void assert_closed()
{
    if( ifdef_level!=0 )
        error("Unclosed #if directive at EOF");
}

static void ifdef_push()
{
    ++ifdef_level;
}
static void ifdef_pop()
{
    --ifdef_level;
    assert_endif();
}



static char *raw_symbol=0;

static void raw_beg(int state)
{
    raw_symbol=strdup(yytext);
    statepush(state);
}

static void raw_end()
{
    if( 0==strcmp(raw_symbol,yytext) )
    {
        free(raw_symbol);
        statepop();
    }
}

#line 869 "ppo/input.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
static int yy_ignored_retcode;
#define ECHO (yy_ignored_retcode=fwrite(yytext,yyleng,1,yyout))
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
     {
     register yy_state_type yy_current_state;
     register char *yy_cp, *yy_bp;
     register int yy_act;

#line 226 "./input.lex"


#line 1027 "ppo/input.cpp"

     if ( yy_init )
             {
             yy_init = 0;

#ifdef YY_USER_INIT
             YY_USER_INIT;
#endif

             if ( ! yy_start )
                     yy_start = 1;   /* first start state */

             if ( ! yyin )
                     yyin = stdin;

             if ( ! yyout )
                     yyout = stdout;

             if ( ! yy_current_buffer )
                     yy_current_buffer =
                             yy_create_buffer( yyin, YY_BUF_SIZE );

             yy_load_buffer_state();
             }

     while ( 1 )             /* loops until end-of-file is reached */
             {
             yy_cp = yy_c_buf_p;

             /* Support of yytext. */
             *yy_cp = yy_hold_char;

             /* yy_bp points to the position in yy_ch_buf of the start of
              * the current run.
              */
             yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 275 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 704 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

             YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:   /* This label is used only to access EOF actions. */


             switch ( yy_act )
     { /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 228 "./input.lex"
{outstr(yytext);raw_beg(st_raw);}
	YY_BREAK

case 2:
YY_RULE_SETUP
#line 230 "./input.lex"
{outstr(yytext);raw_end();}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 231 "./input.lex"
outchar(*yytext);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 232 "./input.lex"
outchar(*yytext);
	YY_BREAK


case 5:
YY_RULE_SETUP
#line 235 "./input.lex"
{raw_end();}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 236 "./input.lex"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 237 "./input.lex"

	YY_BREAK

case 8:
YY_RULE_SETUP
#line 241 "./input.lex"
statepush(st_incl);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 242 "./input.lex"
{ifdef_push();statepush(st_ifdef);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 243 "./input.lex"
{ifdef_push();statepush(st_ifndef);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 244 "./input.lex"
{ifdef_push();statepush(st_ifeq);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 245 "./input.lex"
{ifdef_push();statepush(st_ifneq);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 246 "./input.lex"
{assert_else();statepush(st_waitendif);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 247 "./input.lex"
{ifdef_pop();}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 249 "./input.lex"
{if(outtype==0){outtype=1;}else{outstr(yytext);}}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 250 "./input.lex"
{if(outtype==0){outtype=2;}else{outstr(yytext);}}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 251 "./input.lex"
{if(outtype==0){outtype=2;}else{outstr(yytext);}}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 252 "./input.lex"
{if(outtype==0){outtype=3;}else{outstr(yytext);}}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 253 "./input.lex"
{if(outtype==0){outtype=3;}else{outstr(yytext);}}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 254 "./input.lex"
{if(outtype==0){outtype=4;}else{outstr(yytext);}}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 257 "./input.lex"
//comment
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 258 "./input.lex"
//folytató //comment
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 259 "./input.lex"
{outtrim();if(reproctxt==0){outchar(';');}else{printbuf();}} //szétválasztó
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 260 "./input.lex"
printbuf(); //egysoros 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 261 "./input.lex"
statepush(st_comment); //többsoros 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 262 "./input.lex"
outstr(yytext);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 263 "./input.lex"
printbuf();
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 264 "./input.lex"
outchar(*yytext);
	YY_BREAK

case 29:
YY_RULE_SETUP
#line 268 "./input.lex"

	YY_BREAK
case 30:
YY_RULE_SETUP
#line 269 "./input.lex"

	YY_BREAK
case 31:
YY_RULE_SETUP
#line 270 "./input.lex"
outstr("/**/");statepop(); 
	YY_BREAK


case 32:
YY_RULE_SETUP
#line 275 "./input.lex"

	YY_BREAK
case 33:
YY_RULE_SETUP
#line 276 "./input.lex"
{procinclude();}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 277 "./input.lex"
{procinclude();statepush(st_comment);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 278 "./input.lex"
error("Syntax ERROR in #include directive"); 
	YY_BREAK


case 36:
YY_RULE_SETUP
#line 282 "./input.lex"

	YY_BREAK
case 37:
YY_RULE_SETUP
#line 283 "./input.lex"
{procifdef(0);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 284 "./input.lex"
{procifdef(0);statepush(st_comment);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 285 "./input.lex"
error("Syntax ERROR in #ifdef directive");
	YY_BREAK


case 40:
YY_RULE_SETUP
#line 289 "./input.lex"

	YY_BREAK
case 41:
YY_RULE_SETUP
#line 290 "./input.lex"
{procifdef(1);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 291 "./input.lex"
{procifdef(1);statepush(st_comment);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 292 "./input.lex"
error("Syntax ERROR in #ifndef directive");
	YY_BREAK


case 44:
YY_RULE_SETUP
#line 296 "./input.lex"

	YY_BREAK
case 45:
YY_RULE_SETUP
#line 297 "./input.lex"
{procifdef(2);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 298 "./input.lex"
{procifdef(2);statepush(st_comment);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 299 "./input.lex"
error("Syntax ERROR in #ifeq directive");
	YY_BREAK


case 48:
YY_RULE_SETUP
#line 304 "./input.lex"

	YY_BREAK
case 49:
YY_RULE_SETUP
#line 305 "./input.lex"
{procifdef(3);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 306 "./input.lex"
{procifdef(3);statepush(st_comment);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 307 "./input.lex"
error("Syntax ERROR in #ifneq directive");
	YY_BREAK


case 52:
YY_RULE_SETUP
#line 312 "./input.lex"
{assert_else();statepop();}
	YY_BREAK


case 53:
YY_RULE_SETUP
#line 317 "./input.lex"
{ifdef_pop();statepop();}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 318 "./input.lex"
{ifdef_push();statepush(st_waitendif);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 319 "./input.lex"
{ifdef_push();statepush(st_waitendif);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 320 "./input.lex"
{ifdef_push();statepush(st_waitendif);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 321 "./input.lex"
{ifdef_push();statepush(st_waitendif);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 322 "./input.lex"

	YY_BREAK
case 59:
YY_RULE_SETUP
#line 323 "./input.lex"

	YY_BREAK
case 60:
YY_RULE_SETUP
#line 324 "./input.lex"
statepush(st_comment); //többsoros   
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 325 "./input.lex"
{raw_beg(st_waitraw);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 326 "./input.lex"

	YY_BREAK
case 63:
YY_RULE_SETUP
#line 327 "./input.lex"

	YY_BREAK

case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(st_incl):
case YY_STATE_EOF(st_ifdef):
case YY_STATE_EOF(st_ifndef):
case YY_STATE_EOF(st_ifeq):
case YY_STATE_EOF(st_ifneq):
case YY_STATE_EOF(st_waitelse):
case YY_STATE_EOF(st_waitendif):
case YY_STATE_EOF(st_comment):
case YY_STATE_EOF(st_raw):
case YY_STATE_EOF(st_waitraw):
#line 331 "./input.lex"
{

    if( YYSTATE==st_raw )
    {
        char buf[256];
        sprintf(buf,"Unclosed long string %s at EOF",raw_symbol);
        error(buf);
    }

    printbuf();

    printf("\n%sEnd %s ",tabular(include_stack_ptr),getfilename());
     
    if( --include_stack_ptr<0 )
    {
        assert_closed();
        outtype=0;
        outchar('\n');
        printbuf();
        yyterminate();
    }
    else
    {
        fclose(yyin);
        yy_delete_buffer( YY_CURRENT_BUFFER );
        yy_switch_to_buffer(include_stack[include_stack_ptr] );
        free(fname_stack[include_stack_ptr]);
        yylineno=lnumber_stack[include_stack_ptr];
    }
    include_changed=1;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 363 "./input.lex"
ECHO;
	YY_BREAK
#line 1503 "ppo/input.cpp"

     case YY_END_OF_BUFFER:
             {
             /* Amount of text matched not including the EOB char. */
             int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

             /* Undo the effects of YY_DO_BEFORE_ACTION. */
             *yy_cp = yy_hold_char;
             YY_RESTORE_YY_MORE_OFFSET

             if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
                     {
                     /* We're scanning a new file or input source.  It's
                      * possible that this happened because the user
                      * just pointed yyin at a new source and called
                      * yylex().  If so, then we have to assure
                      * consistency between yy_current_buffer and our
                      * globals.  Here is the right place to do so, because
                      * this is the first action (other than possibly a
                      * back-up) that will match for the new input source.
                      */
                     yy_n_chars = yy_current_buffer->yy_n_chars;
                     yy_current_buffer->yy_input_file = yyin;
                     yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
                     }

             /* Note that here we test for yy_c_buf_p "<=" to the position
              * of the first EOB in the buffer, since yy_c_buf_p will
              * already have been incremented past the NUL character
              * (since all states make transitions on EOB to the
              * end-of-buffer state).  Contrast this with the test
              * in input().
              */
             if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
                     { /* This was really a NUL. */
                     yy_state_type yy_next_state;

                     yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

                     yy_current_state = yy_get_previous_state();

                     /* Okay, we're now positioned to make the NUL
                      * transition.  We couldn't have
                      * yy_get_previous_state() go ahead and do it
                      * for us because it doesn't know how to deal
                      * with the possibility of jamming (and we don't
                      * want to build jamming into it because then it
                      * will run more slowly).
                      */

                     yy_next_state = yy_try_NUL_trans( yy_current_state );

                     yy_bp = yytext_ptr + YY_MORE_ADJ;

                     if ( yy_next_state )
                             {
                             /* Consume the NUL. */
                             yy_cp = ++yy_c_buf_p;
                             yy_current_state = yy_next_state;
                             goto yy_match;
                             }

                     else
                             {
				yy_cp = yy_c_buf_p;
                             goto yy_find_action;
                             }
                     }

             else switch ( yy_get_next_buffer() )
                     {
                     case EOB_ACT_END_OF_FILE:
                             {
                             yy_did_buffer_switch_on_eof = 0;

                             if ( yywrap() )
                                     {
                                     /* Note: because we've taken care in
                                      * yy_get_next_buffer() to have set up
                                      * yytext, we can now set up
                                      * yy_c_buf_p so that if some total
                                      * hoser (like flex itself) wants to
                                      * call the scanner after we return the
                                      * YY_NULL, it'll still work - another
                                      * YY_NULL will get returned.
                                      */
                                     yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

                                     yy_act = YY_STATE_EOF(YY_START);
                                     goto do_action;
                                     }

                             else
                                     {
                                     if ( ! yy_did_buffer_switch_on_eof )
                                             YY_NEW_FILE;
                                     }
                             break;
                             }

                     case EOB_ACT_CONTINUE_SCAN:
                             yy_c_buf_p =
                                     yytext_ptr + yy_amount_of_matched_text;

                             yy_current_state = yy_get_previous_state();

                             yy_cp = yy_c_buf_p;
                             yy_bp = yytext_ptr + YY_MORE_ADJ;
                             goto yy_match;

                     case EOB_ACT_LAST_MATCH:
                             yy_c_buf_p =
                             &yy_current_buffer->yy_ch_buf[yy_n_chars];

                             yy_current_state = yy_get_previous_state();

                             yy_cp = yy_c_buf_p;
                             yy_bp = yytext_ptr + YY_MORE_ADJ;
                             goto yy_find_action;
                     }
             break;
             }

     default:
             YY_FATAL_ERROR(
                     "fatal flex scanner internal error--no action found" );
     } /* end of action switch */
             } /* end of scanning one token */
     } /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *   EOB_ACT_LAST_MATCH -
 *   EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *   EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
     {
     register char *dest = yy_current_buffer->yy_ch_buf;
     register char *source = yytext_ptr;
     register int number_to_move, i;
     int ret_val;

     if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
             YY_FATAL_ERROR(
             "fatal flex scanner internal error--end of buffer missed" );

     if ( yy_current_buffer->yy_fill_buffer == 0 )
             { /* Don't try to fill the buffer, so this is an EOF. */
             if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
                     {
                     /* We matched a single character, the EOB, so
                      * treat this as a final EOF.
                      */
                     return EOB_ACT_END_OF_FILE;
                     }

             else
                     {
                     /* We matched some text prior to the EOB, first
                      * process it.
                      */
                     return EOB_ACT_LAST_MATCH;
                     }
             }

     /* Try to read more data. */

     /* First move last chars to start of buffer. */
     number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

     for ( i = 0; i < number_to_move; ++i )
             *(dest++) = *(source++);

     if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
             /* don't do the read, it's not guaranteed to return an EOF,
              * just force an EOF
              */
             yy_current_buffer->yy_n_chars = yy_n_chars = 0;

     else
             {
             int num_to_read =
                     yy_current_buffer->yy_buf_size - number_to_move - 1;

             while ( num_to_read <= 0 )
                     { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
                     YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

                     /* just a shorter name for the current buffer */
                     YY_BUFFER_STATE b = yy_current_buffer;

                     int yy_c_buf_p_offset =
                             (int) (yy_c_buf_p - b->yy_ch_buf);

                     if ( b->yy_is_our_buffer )
                             {
                             int new_size = b->yy_buf_size * 2;

                             if ( new_size <= 0 )
                                     b->yy_buf_size += b->yy_buf_size / 8;
                             else
                                     b->yy_buf_size *= 2;

                             b->yy_ch_buf = (char *)
                                     /* Include room in for 2 EOB chars. */
                                     yy_flex_realloc( (void *) b->yy_ch_buf,
                                                      b->yy_buf_size + 2 );
                             }
                     else
                             /* Can't grow it, we don't own it. */
                             b->yy_ch_buf = 0;

                     if ( ! b->yy_ch_buf )
                             YY_FATAL_ERROR(
                             "fatal error - scanner input buffer overflow" );

                     yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

                     num_to_read = yy_current_buffer->yy_buf_size -
                                             number_to_move - 1;
#endif
                     }

             if ( num_to_read > YY_READ_BUF_SIZE )
                     num_to_read = YY_READ_BUF_SIZE;

             /* Read in more data. */
             YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
                     yy_n_chars, num_to_read );

             yy_current_buffer->yy_n_chars = yy_n_chars;
             }

     if ( yy_n_chars == 0 )
             {
             if ( number_to_move == YY_MORE_ADJ )
                     {
                     ret_val = EOB_ACT_END_OF_FILE;
                     yyrestart( yyin );
                     }

             else
                     {
                     ret_val = EOB_ACT_LAST_MATCH;
                     yy_current_buffer->yy_buffer_status =
                             YY_BUFFER_EOF_PENDING;
                     }
             }

     else
             ret_val = EOB_ACT_CONTINUE_SCAN;

     yy_n_chars += number_to_move;
     yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
     yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

     yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

     return ret_val;
     }


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
     {
     register yy_state_type yy_current_state;
     register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

     for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
             {
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 275 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
             }

     return yy_current_state;
     }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *   next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
     {
     register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 275 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 274);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

     return yy_is_jam ? 0 : yy_current_state;
     }


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
     {
     register char *yy_cp = yy_c_buf_p;

     /* undo effects of setting up yytext */
     *yy_cp = yy_hold_char;

     if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
             { /* need to shift things up to make room */
             /* +2 for EOB chars. */
             register int number_to_move = yy_n_chars + 2;
             register char *dest = &yy_current_buffer->yy_ch_buf[
                                     yy_current_buffer->yy_buf_size + 2];
             register char *source =
                             &yy_current_buffer->yy_ch_buf[number_to_move];

             while ( source > yy_current_buffer->yy_ch_buf )
                     *--dest = *--source;

             yy_cp += (int) (dest - source);
             yy_bp += (int) (dest - source);
             yy_current_buffer->yy_n_chars =
                     yy_n_chars = yy_current_buffer->yy_buf_size;

             if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
                     YY_FATAL_ERROR( "flex scanner push-back overflow" );
             }

     *--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

     yytext_ptr = yy_bp;
     yy_hold_char = *yy_cp;
     yy_c_buf_p = yy_cp;
     }
#endif       /* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
     {
     int c;

     *yy_c_buf_p = yy_hold_char;

     if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
             {
             /* yy_c_buf_p now points to the character we want to return.
              * If this occurs *before* the EOB characters, then it's a
              * valid NUL; if not, then we've hit the end of the buffer.
              */
             if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
                     /* This was really a NUL. */
                     *yy_c_buf_p = '\0';

             else
                     { /* need more input */
                     int offset = yy_c_buf_p - yytext_ptr;
                     ++yy_c_buf_p;

                     switch ( yy_get_next_buffer() )
                             {
                             case EOB_ACT_LAST_MATCH:
                                     /* This happens because yy_g_n_b()
                                      * sees that we've accumulated a
                                      * token and flags that we need to
                                      * try matching the token before
                                      * proceeding.  But for input(),
                                      * there's no matching to consider.
                                      * So convert the EOB_ACT_LAST_MATCH
                                      * to EOB_ACT_END_OF_FILE.
                                      */

                                     /* Reset buffer status. */
                                     yyrestart( yyin );

                                     /* fall through */

                             case EOB_ACT_END_OF_FILE:
                                     {
                                     if ( yywrap() )
                                             return EOF;

                                     if ( ! yy_did_buffer_switch_on_eof )
                                             YY_NEW_FILE;
#ifdef __cplusplus
                                     return yyinput();
#else
                                     return input();
#endif
                                     }

                             case EOB_ACT_CONTINUE_SCAN:
                                     yy_c_buf_p = yytext_ptr + offset;
                                     break;
                             }
                     }
             }

     c = *(unsigned char *) yy_c_buf_p;      /* cast for 8-bit char's */
     *yy_c_buf_p = '\0';    /* preserve yytext */
     yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

     return c;
     }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
     {
     if ( ! yy_current_buffer )
             yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

     yy_init_buffer( yy_current_buffer, input_file );
     yy_load_buffer_state();
     }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
     {
     if ( yy_current_buffer == new_buffer )
             return;

     if ( yy_current_buffer )
             {
             /* Flush out information for old buffer. */
             *yy_c_buf_p = yy_hold_char;
             yy_current_buffer->yy_buf_pos = yy_c_buf_p;
             yy_current_buffer->yy_n_chars = yy_n_chars;
             }

     yy_current_buffer = new_buffer;
     yy_load_buffer_state();

     /* We don't actually know whether we did this switch during
      * EOF (yywrap()) processing, but the only time this flag
      * is looked at is after yywrap() is called, so it's safe
      * to go ahead and always set it.
      */
     yy_did_buffer_switch_on_eof = 1;
     }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
     {
     yy_n_chars = yy_current_buffer->yy_n_chars;
     yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
     yyin = yy_current_buffer->yy_input_file;
     yy_hold_char = *yy_c_buf_p;
     }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
     {
     YY_BUFFER_STATE b;

     b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
     if ( ! b )
             YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

     b->yy_buf_size = size;

     /* yy_ch_buf has to be 2 characters longer than the size given because
      * we need to put in 2 end-of-buffer characters.
      */
     b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
     if ( ! b->yy_ch_buf )
             YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

     b->yy_is_our_buffer = 1;

     yy_init_buffer( b, file );

     return b;
     }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
     {
     if ( ! b )
             return;

     if ( b == yy_current_buffer )
             yy_current_buffer = (YY_BUFFER_STATE) 0;

     if ( b->yy_is_our_buffer )
             yy_flex_free( (void *) b->yy_ch_buf );

     yy_flex_free( (void *) b );
     }


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
//extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


     {
     yy_flush_buffer( b );

     b->yy_input_file = file;
     b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
     b->yy_is_interactive = 1;
#else
//#if YY_NEVER_INTERACTIVE
     b->yy_is_interactive = 0;
//#else
//     b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
//#endif
#endif
     }


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

     {
     if ( ! b )
             return;

     b->yy_n_chars = 0;

     /* We always need two end-of-buffer characters.  The first causes
      * a transition to the end-of-buffer state.  The second causes
      * a jam in that state.
      */
     b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
     b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

     b->yy_buf_pos = &b->yy_ch_buf[0];

     b->yy_at_bol = 1;
     b->yy_buffer_status = YY_BUFFER_NEW;

     if ( b == yy_current_buffer )
             yy_load_buffer_state();
     }


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
     {
     YY_BUFFER_STATE b;

     if ( size < 2 ||
          base[size-2] != YY_END_OF_BUFFER_CHAR ||
          base[size-1] != YY_END_OF_BUFFER_CHAR )
             /* They forgot to leave room for the EOB's. */
             return 0;

     b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
     if ( ! b )
             YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

     b->yy_buf_size = size - 2;      /* "- 2" to take care of EOB's */
     b->yy_buf_pos = b->yy_ch_buf = base;
     b->yy_is_our_buffer = 0;
     b->yy_input_file = 0;
     b->yy_n_chars = b->yy_buf_size;
     b->yy_is_interactive = 0;
     b->yy_at_bol = 1;
     b->yy_fill_buffer = 0;
     b->yy_buffer_status = YY_BUFFER_NEW;

     yy_switch_to_buffer( b );

     return b;
     }
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
     {
     int len;
     for ( len = 0; yy_str[len]; ++len )
             ;

     return yy_scan_bytes( yy_str, len );
     }
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
     {
     YY_BUFFER_STATE b;
     char *buf;
     yy_size_t n;
     int i;

     /* Get memory for full buffer, including space for trailing EOB's. */
     n = len + 2;
     buf = (char *) yy_flex_alloc( n );
     if ( ! buf )
             YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

     for ( i = 0; i < len; ++i )
             buf[i] = bytes[i];

     buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

     b = yy_scan_buffer( buf, n );
     if ( ! b )
             YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

     /* It's okay to grow etc. this buffer, and we should throw it
      * away when we're done.
      */
     b->yy_is_our_buffer = 1;

     return b;
     }
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
     {
     if ( yy_start_stack_ptr >= yy_start_stack_depth )
             {
             yy_size_t new_size;

             yy_start_stack_depth += YY_START_STACK_INCR;
             new_size = yy_start_stack_depth * sizeof( int );

             if ( ! yy_start_stack )
                     yy_start_stack = (int *) yy_flex_alloc( new_size );

             else
                     yy_start_stack = (int *) yy_flex_realloc(
                                     (void *) yy_start_stack, new_size );

             if ( ! yy_start_stack )
                     YY_FATAL_ERROR(
                     "out of memory expanding start-condition stack" );
             }

     yy_start_stack[yy_start_stack_ptr++] = YY_START;

     BEGIN(new_state);
     }
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
     {
     if ( --yy_start_stack_ptr < 0 )
             YY_FATAL_ERROR( "start-condition stack underflow" );

     BEGIN(yy_start_stack[yy_start_stack_ptr]);
     }
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
     {
     return yy_start_stack[yy_start_stack_ptr - 1];
     }
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
     {
     (void) fprintf( stderr, "%s\n", msg );
     exit( YY_EXIT_FAILURE );
     }



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
     do \
             { \
             /* Undo effects of setting up yytext. */ \
             yytext[yyleng] = yy_hold_char; \
             yy_c_buf_p = yytext + n; \
             yy_hold_char = *yy_c_buf_p; \
             *yy_c_buf_p = '\0'; \
             yyleng = n; \
             } \
     while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
     {
     register int i;
     for ( i = 0; i < n; ++i )
             s1[i] = s2[i];
     }
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
     {
     register int n;
     for ( n = 0; s[n]; ++n )
             ;

     return n;
     }
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
     {
     return (void *) malloc( size );
     }

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
     {
     /* The cast to (char *) in the following accommodates both
      * implementations that use char* generic pointers, and those
      * that use void* generic pointers.  It works with the latter
      * because both ANSI C and C++ allow castless assignment from
      * any pointer type to void*, and deal with argument conversions
      * as though doing an assignment.
      */
     return (void *) realloc( (char *) ptr, size );
     }

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
     {
     free( ptr );
     }

#if YY_MAIN
int main()
     {
     yylex();
     return 0;
     }
#endif
#line 363 "./input.lex"


//---------------------------------------------------------------------------
void _clp_processing(int argno) 
{
    CCC_PROLOG("processing",1);
    _clp_convertfspec2nativeformat(1);

    filein=_parb(1);
    
    //FONTOS
    //a static változók megfelelő inicializálása, 
    //másképp a program nem hívható többször
    
    printf("\nBeg %s ",filein);

    include_changed=0;
    include_stack_ptr=0;
    state_stack_ptr=0;
    outbuf_idx=0;
    outlineno=0;
    outtype=0;
    yylineno=1;
 
    yyin=fopen(filein,"r");
    if( !yyin )
    {
        yylineno=0;
        error("File not found");
    }

    yylex();

    _ret();
    CCC_EPILOG();
}


//---------------------------------------------------------------------------
static void outbuf_resize(int x)
{
    while(outbuf_idx+x+1>outbuf_siz)
    {
        outbuf=(char*)realloc(outbuf,outbuf_siz+=1024);
    }
}

//---------------------------------------------------------------------------
static void outchar(int c)
{
    if( outbuf_idx==0 && reproctxt==0 )
    {
        outlineno=yylineno;
    }
    outbuf_resize(1);
    outbuf[outbuf_idx]=c;
    outbuf_idx++;
}

//---------------------------------------------------------------------------
static void outtrim()
{
    while( (outbuf!=0) &&
           (outbuf_idx>0) && 
           ((outbuf[outbuf_idx-1]==' ') || (outbuf[outbuf_idx-1]=='\t')) )
    {
        outbuf_idx--;
    }
}

//---------------------------------------------------------------------------
static void outstr(const char *s)
{
    if( outbuf_idx==0 && reproctxt==0 )
    {
        outlineno=yylineno;
    }
    int len=strlen(s);
    outbuf_resize(len);
    memcpy(outbuf+outbuf_idx,s,len);
    outbuf_idx+=len;
}
 

//---------------------------------------------------------------------------
static int outempty()
{
    outchar(0);
    int c;
    char *p=outbuf;
    while( ((c=*p)==' ')||(c=='\t') ) p++;
    return !c;  //1, ha a string üres
}


//---------------------------------------------------------------------------
static void printbuf()
{
    if( !outempty() )
    {
        static int lastlineno=0;

        binaryn(outbuf);

        if( outtype==0 ) //normál programsor
        {
            ++lastlineno;
        
            if( include_changed || (lastlineno!=outlineno)  )
            {
                include_changed=0;
                lastlineno=outlineno;
                number(outlineno);
                stringnb(getfilename());
                _clp_nextline(2);
                pop();
            }
            counter();
            _clp_prepro(1); 
        }

        else if( outtype==1 ) //#define direktíva
        {
            _clp_define(1);
        }
        else if( outtype==2 ) //#xtranslate direktíva 
        {
            logical(0);
            _clp_translate(2);
        }
        else if( outtype==3 ) //#xcommand direktíva 
        {
            logical(1);
            _clp_translate(2);
        }
        else if( outtype==4 ) //#undef direktíva 
        {
            _clp_undef(1);
        }
 
        pop();
        outtype=0;
    }

    outbuf_idx=0;
}
 
//---------------------------------------------------------------------------
void error(const char*txt)
{   
    printf("\n%s",txt);
    printf("\nFile(%s) Line(%d) [%s]",getfilename(),yylineno,yytext);
    exit(1);
}

//---------------------------------------------------------------------------
void _clp_error(int argno) //ugyanaz Clipperből
{
    CCC_PROLOG("error",1);
    str2bin(base);
    char *txt=_parb(1);
    error(txt);
    _ret();
    CCC_EPILOG();
}
 

//---------------------------------------------------------------------------
static void counter()
{
    static int cnt=0;

    if( (++cnt%50)==0 )
    {
         printf(">");
    }
}    

//---------------------------------------------------------------------------
static void statepush(int state)
{
    if( state_stack_ptr<MAX_STATE_DEPTH )
    {
        state_stack[state_stack_ptr++]=YYSTATE;
        BEGIN(state); 
        //printf("\npush BEGIN %3d %s %d %d",yylineno,getfilename(),state_stack_ptr,state);
    }
    else
    {
        error("LEX state stack overflow");
    }
}

//---------------------------------------------------------------------------
static void statepop()
{
    if( --state_stack_ptr>=0 )
    {
        int state=state_stack[state_stack_ptr]; 
        BEGIN(state);
        //printf("\npop  BEGIN %3d %s %d %d",yylineno,getfilename(),state_stack_ptr,state);
    }
    else
    {
        error("LEX state stack underflow");
    }
}

//---------------------------------------------------------------------------
void _clp_reproctxt(int argno)
{
    CCC_PROLOG("reproctxt",1);
    int cursize=reproclen;
    reproctxt=(char*)realloc(reproctxt,reproclen=cursize+_parblen(1));
    memmove(reproctxt+cursize,_parb(1),_parblen(1));
    CCC_EPILOG();
}

//---------------------------------------------------------------------------
static void procinclude()
{
    if( include_stack_ptr>=MAX_INCLUDE_DEPTH )
    {
        error("Includes nested too deeply");
    }

    int i=1;while( yytext[i]!='"')i++;yytext[i]=0;
    stringnb(yytext+1);                                     //CCC-STACK++
    _clp_searchinclude(1);
    _clp_convertfspec2nativeformat(1);
    char *fspec=BINARYPTR(TOP());
    printf("\n%sBeg %s ",tabular(include_stack_ptr+1),fspec);
    yyin=fopen(fspec,"r");

    if( !yyin )
    {
        error("Include file not found");
    }

    include_stack[include_stack_ptr]=YY_CURRENT_BUFFER;
    fname_stack[include_stack_ptr]=strdup(fspec);
    lnumber_stack[include_stack_ptr]=yylineno;

    include_stack_ptr++;

    yylineno=1;
    yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE));

    statepop();
    pop();                                                  //CCC-STACK--

    number(1);
    stringnb(getfilename());
    _clp_nextline(2);
    pop();
    include_changed=1;
}

 
//---------------------------------------------------------------------------
static char *getfilename()
{
    if( include_stack_ptr>0 )
    {
        return fname_stack[include_stack_ptr-1];
    }

    return filein;
}

//---------------------------------------------------------------------------
static char *tabular(int pos)
{
    static char tab[128];
    int i;
    for( i=0; i<4*pos; i++ )
    {
        tab[i]=' ';
    }
    tab[i]=0;
    return &tab[0];
}
 

//---------------------------------------------------------------------------
static void procifdef(int type)
{
    statepop();

    int def=0;    
    stringnb(yytext);
    _clp_searchdefine(1);
    if( TOP()->type==TYPE_FLAG )
    {
        def=(TOP()->data.flag)?2:1;
    }
    pop();
  
    //def==0 -> nem definiált
    //def==1 -> definiált, de nem egyenlő
    //def==2 -> definiált, és egyenlő

    if( ((type==0) && !def   ) ||  //#ifdef 
        ((type==1) &&  def   ) ||  //#ifndef 
        ((type==2) &&  def!=2) ||  //#ifeq
        ((type==3) &&  def==2) )   //#ifneq
    {
        statepush(st_waitelse); 
    }
}


//---------------------------------------------------------------------------

