#define EXPR                            1
#define SPACE                           2
#define EXCL                            3
#define MINUS                           4
#define PLUS                            5
#define AT                              6
#define LBRACKET                        7
#define RBRACKET                        8
#define SLASH                           9
#define BSLASH                         10
#define DOT                            11
#define PIPE                           12
#define STAR                           13
#define MODULO                         14
#define POWER                          15
#define DOLLAR                         16
#define GT                             17
#define LT                             18
#define COLON                          19
#define EQUAL                          20
#define LPAR                           21
#define RPAR                           22
#define DOTDOT                         23
#define LBRACE                         24
#define RBRACE                         25
#define COMMA                          26
