#define EXPR                            1
#define SPACE                           2
#define EXCL                            3
#define MINUS                           4
#define PLUS                            5
#define AT                              6
#define SLASH                           7
#define BSLASH                          8
#define DOT                             9
#define STAR                           10
#define MODULO                         11
#define POWER                          12
#define DOLLAR                         13
#define GT                             14
#define LT                             15
#define COLON                          16
#define EQUAL                          17
#define LPAR                           18
#define RPAR                           19
#define LBRACKET                       20
#define RBRACKET                       21
#define DOTDOT                         22
#define LBRACE                         23
#define RBRACE                         24
#define PIPE                           25
#define COMMA                          26
