#!/bin/bash

#minimális CCC környezet a root-nak sudo-hoz

export CCCDIR=/opt/ccc3
export CCCUNAME=linux
export CCCBIN=lin
export PATH=$CCCDIR/usr/bin/$CCCUNAME:$PATH
export LD_LIBRARY_PATH=$CCCDIR/usr/lib/$CCCBIN:$LD_LIBRARY_PATH

webcon.exe -l 4433 -p 8080 -k cert/localhost.pem #-cp cert

