#!/bin/bash
bapp_unix_.b @parlib.bld

bapp_unix_.b    \
    -xbt2dbf    \
    -xbt2txt    \
    -xbtcheck   \
    -xbtdecrypt \
    -xbtencrypt \
    -xbthead    \
    -xbti       \
    -xbtlink    \
    -xbtmemo    \
    -xbtpack    \
    -xbtpage    \
    -xbtstat    \
    -xbtwalk    \
    -xtsema     \
    @parexe.bld


bapp_unixc.b -xtstru -xtview -xbtp  @parexe.bld  -bccc${CCCVER}_btbtxui
