

namespace crm


***************************************************************************************
function orszagkod()

static orszagkod:={;
"AD - Andorra"                           ,;
"AE - Egyesült Arab Emírségek"           ,;
"AF - Afganisztán"                       ,;
"AL - Albánia"                           ,;
"AM - Örményország"                      ,;
"AN - Holland Antillák"                  ,;
"AR - Argentína"                         ,;
"AT - Ausztria"                          ,;
"AU - Ausztrália"                        ,;
"AZ - Azerbajdzsán"                      ,;
"BA - Bosznia-Hercegovina"               ,;
"BB - Barbadosz"                         ,;
"BE - Belgium"                           ,;
"BF - Burkina Faso"                      ,;
"BG - Bulgária"                          ,;
"BH - Bahrain"                           ,;
"BI - Burundi"                           ,;
"BJ - Benin"                             ,;
"BM - Bermuda"                           ,;
"BO - Bolívia"                           ,;
"BR - Brazília"                          ,;
"BS - Bahama-szigetek Nassau"            ,;
"BW - Botswana"                          ,;
"BY - Belorusszia"                       ,;
"BZ - Belize"                            ,;
"CA - Kanada"                            ,;
"CD - Kongói Demokratikus Közt."         ,;
"CF - Közép-Afrikai Köztársaság"         ,;
"CG - Kongo"                             ,;
"CH - Svájc"                             ,;
"CI - Elefántcsontpart"                  ,;
"CL - Chile"                             ,;
"CM - Kamerun"                           ,;
"CN - Kína"                              ,;
"CO - Kolumbia"                          ,;
"CR - Costa Rica"                        ,;
"CS - Szerbia-Montenegró"                ,;
"CU - Kuba"                              ,;
"CV - Zöldfoki Köztársaság"              ,;
"CY - Ciprus"                            ,;
"CZ - Csehország"                        ,;
"DE - Németország"                       ,;
"DJ - Dzsibuti"                          ,;
"DK - Dánia"                             ,;
"DM - Dominika"                          ,;
"DO - Dominikai Köztársaság"             ,;
"EC - Equador"                           ,;
"EE - Észtország"                        ,;
"ER - Eritrea"                           ,;
"ES - Spanyolország"                     ,;
"ET - Etiópia"                           ,;
"FI - Finnország"                        ,;
"FK - Falkland-szigetek"                 ,;
"FM - Mikronézia"                        ,;
"FR - Franciaország"                     ,;
"GA - Gabon"                             ,;
"GB - Egyesült Királyság"                ,;
"GD - Grenada"                           ,;
"GE - Grúzia"                            ,;
"GG - Guernsey"                          ,;
"GH - Ghana"                             ,;
"GI - Gibraltár"                         ,;
"GM - Gambia"                            ,;
"GN - Guinea"                            ,;
"GQ - Egyenlítői Guinea"                 ,;
"GR - Görögország"                       ,;
"GT - Guatemala"                         ,;
"GW - Guinea-Bissau"                     ,;
"GY - Guyana"                            ,;
"HK - Hongkong"                          ,;
"HN - Honduras"                          ,;
"HR - Horvátország"                      ,;
"HT - Haiti"                             ,;
"HU - Magyarország"                      ,;
"ID - Indonézia"                         ,;
"IE - Írország"                          ,;
"IL - Izrael"                            ,;
"IM - Isle of Man"                       ,;
"IN - India"                             ,;
"IQ - Irak"                              ,;
"IR - Irán"                              ,;
"IS - Izland"                            ,;
"IT - Olaszország"                       ,;
"JE - Jersey"                            ,;
"JM - Jamaica"                           ,;
"JO - Jordánia"                          ,;
"JP - Japán"                             ,;
"KE - Kenya"                             ,;
"KG - Kirgizisztán"                      ,;
"KH - Kambodzsa"                         ,;
"KP - Koreai NDK"                        ,;
"KR - Dél-Korea"                         ,;
"KW - Kuwait"                            ,;
"KY - Kajmán-szigetek"                   ,;
"KZ - Kazahsztán"                        ,;
"LA - Laosz"                             ,;
"LB - Libanon"                           ,;
"LI - Liechtenstein"                     ,;
"LK - Sri Lanka"                         ,;
"LR - Libéria"                           ,;
"LS - Leshoto"                           ,;
"LT - Litvánia"                          ,;
"LU - Luxembourg"                        ,;
"LV - Lettország"                        ,;
"LY - Líbia"                             ,;
"MD - Moldova"                           ,;
"MG - Malgas Köztársaság"                ,;
"MK - Makedónia"                         ,;
"ML - Mali"                              ,;
"MM - Mianmar"                           ,;
"MN - Mongólia"                          ,;
"MO - Macao"                             ,;
"MR - Mauritánia"                        ,;
"MS - Montserrat"                        ,;
"MT - Málta"                             ,;
"MU - Mautitius"                         ,;
"MV - Maldiv-szigetek"                   ,;
"MW - Malawi"                            ,;
"MX - Mexikó"                            ,;
"MY - Malaysia"                          ,;
"MZ - Mozambik"                          ,;
"NA - Namíbia"                           ,;
"NE - Niger"                             ,;
"NG - Nigéria"                           ,;
"NI - Nikaragua"                         ,;
"NL - Hollandia"                         ,;
"NO - Norvégia"                          ,;
"NP - Nepál"                             ,;
"NZ - Új-Zéland"                         ,;
"OM - Omán"                              ,;
"PA - Panama"                            ,;
"PE - Peru"                              ,;
"PH - Fülöp-szigetek"                    ,;
"PK - Pakisztán"                         ,;
"PL - Lengyelország"                     ,;
"PS - Palesztina"                        ,;
"PT - Portugália"                        ,;
"PY - Paraguay"                          ,;
"QA - Quatar"                            ,;
"RO - Románia"                           ,;
"RU - Oroszország"                       ,;
"RW - Ruanda"                            ,;
"SA - Szaud-Arábia"                      ,;
"SC - Seychelle-szigetek"                ,;
"SD - Szudán"                            ,;
"SE - Svédország"                        ,;
"SG - Szingapur"                         ,;
"SH - Saint Helena"                      ,;
"SI - Szlovénia"                         ,;
"SK - Szlovákia"                         ,;
"SL - Sierra Leone"                      ,;
"SM - San Marino"                        ,;
"SN - Szenegambia"                       ,;
"SO - Szomália"                          ,;
"SR - Suriname"                          ,;
"SV - Salvador"                          ,;
"SY - Szíria"                            ,;
"SZ - Szvázi"                            ,;
"TD - Csád"                              ,;
"TG - Togo"                              ,;
"TH - Thaiföld"                          ,;
"TJ - Tadzsikisztán"                     ,;
"TM - Türkmenisztán"                     ,;
"TR - Törökország"                       ,;
"TT - Trinidad és Tobago"                ,;
"TW - Taiwan"                            ,;
"TZ - Tanzánia"                          ,;
"UA - Ukrajna"                           ,;
"UG - Uganda"                            ,;
"US - Amerika Egyesült Államok"          ,;
"UY - Uruguay"                           ,;
"UZ - Üzbegisztán"                       ,;
"VA - Vatikán"                           ,;
"VE - Venezuela"                         ,;
"VG - Brit Virgin-szigetek"              ,;
"VN - Vietnámi Köztársaság"              ,;
"VU - Vanuatu"                           ,;
"YE - Jemeni Arab Köztársaság"           ,;
"ZA - Dél-Afrikai Köztársaság"           ,;
"ZM - Zambia"                            ,;
"ZW - Zimbabwe"                          }

    return orszagkod

***************************************************************************************

    