#!/bin/bash
#set -x

#IOSTREAM=iostream-new
#IOSTREAM=iostream-old

FLEX=$CCCDIR/usr/bin/$CCCUNAME/flex.exe

if [ ! -x $FLEX ]; then
    cc  -I .  *.c -o $FLEX
    cp -p flexlexer.h  $CCCDIR/usr/include

    if [ -x $FLEX ]; then
        echo 'flex compiled successfully'
    else
        echo 'flex failed to compile'
    fi
fi
