#!/bin/bash
#set -x

FLEX=$CCCDIR/usr/bin/flex.exe

CFLAGS=
CFLAGS="-Wno-deprecated-non-prototype $CFLAGS"
CFLAGS="-Wno-unknown-warning-option $CFLAGS"

if [ ! -x $FLEX ]; then
    cc $CFLAGS -I .  *.c -o $FLEX
    cp -p flexlexer.h  $CCCDIR/usr/include

    if [ -x $FLEX ]; then
        echo 'flex compiled successfully'
    else
        echo 'flex failed to compile'
    fi
fi
