#!/bin/bash

#cd proto && m && cd ..
#rm -f objlin/ppo2cpp.obj
#rm -f objlin/*.obj
#proto-codegen
#parserinfo

cp metdecl.cpp3 metdecl.cpp
rm objlin/metdecl*

c++app.sh -mppo2cpp  BUILD_EXE=$CCCDIR/usr/bin
