#!/bin/bash

#cd proto && m && cd ..
#rm -f objlin/ppo2cpp.obj
#rm -f objlin/*.obj
#proto-codegen
#parserinfo

cp metdecl.cpp5 metdecl.cpp
rm objlin/metdecl*

bapp_unix0.b -mppo2cpp  "BUILD_EXE=$CCCDIR/usr/bin/$CCCUNAME"
