#define LOWPRECEDENCE                   1
#define UNEXPECTEDCHAR                  2
#define INVALIDENCODING                 3
#define NL                              4
#define DOT                             5
#define DOTDOT                          6
#define COMMA                           7
#define ASSIGN                          8
#define ADDASS                          9
#define SUBASS                         10
#define MULASS                         11
#define DIVASS                         12
#define MODASS                         13
#define COLCOLASS                      14
#define OR                             15
#define AND                            16
#define NOT                            17
#define EQ                             18
#define EQEQ                           19
#define GTEQ                           20
#define LTEQ                           21
#define EXEQ                           22
#define GT                             23
#define LT                             24
#define DOLLAR                         25
#define PLUS                           26
#define MINUS                          27
#define STAR                           28
#define SLASH                          29
#define MODULO                         30
#define DBSTAR                         31
#define DBPLUS                         32
#define DBMINUS                        33
#define LBRACKET                       34
#define COLON                          35
#define COLCOL                         36
#define ARROW                          37
#define HIGHPRECEDENCE                 38
#define NAMESPACE                      39
#define USING                          40
#define SYMBOL                         41
#define STATIC                         42
#define CLANG                          43
#define LPAR                           44
#define RPAR                           45
#define CLASS                          46
#define STCLASS                        47
#define NEW                            48
#define ATTRIB                         49
#define METHOD                         50
#define FUNCTION                       51
#define STFUNCTION                     52
#define LOCAL                          53
#define QUIT                           54
#define RETURN                         55
#define END                            56
#define WHILE                          57
#define FOR                            58
#define TO                             59
#define LOOP                           60
#define EXIT                           61
#define BEGSEQ                         62
#define RECOVER                        63
#define FINALLY                        64
#define IF                             65
#define DOCASE                         66
#define CASE                           67
#define ELSEIF                         68
#define ELSE                           69
#define OTHERWISE                      70
#define STEP                           71
#define RBRACKET                       72
#define AT                             73
#define NUMBER                         74
#define STRING                         75
#define NLSTEXT                        76
#define BINARYX                        77
#define BINARYA                        78
#define TRUE                           79
#define FALSE                          80
#define NIL                            81
#define LBRACE                         82
#define PIPE                           83
#define RBRACE                         84
