#define LOWPRECEDENCE                   1
#define UNEXPECTEDCHAR                  2
#define INVALIDENCODING                 3
#define NL                              4
#define DOT                             5
#define DOTDOT                          6
#define COMMA                           7
#define ASSIGN                          8
#define ADDASS                          9
#define SUBASS                         10
#define MULASS                         11
#define DIVASS                         12
#define MODASS                         13
#define COLCOLASS                      14
#define OR                             15
#define AND                            16
#define NOT                            17
#define EQ                             18
#define EQEQ                           19
#define GTEQ                           20
#define LTEQ                           21
#define EXEQ                           22
#define GT                             23
#define LT                             24
#define DOLLAR                         25
#define PLUS                           26
#define MINUS                          27
#define STAR                           28
#define SLASH                          29
#define MODULO                         30
#define DBSTAR                         31
#define DBPLUS                         32
#define DBMINUS                        33
#define LBRACKET                       34
#define COLON                          35
#define COLCOL                         36
#define ARROW                          37
#define HIGHPRECEDENCE                 38
#define NAMESPACE                      39
#define USING                          40
#define SYMBOL                         41
#define STATIC                         42
#define LPAR                           43
#define RPAR                           44
#define CLASS                          45
#define STCLASS                        46
#define NEW                            47
#define ATTRIB                         48
#define METHOD                         49
#define FUNCTION                       50
#define STFUNCTION                     51
#define LOCAL                          52
#define QUIT                           53
#define RETURN                         54
#define END                            55
#define WHILE                          56
#define FOR                            57
#define TO                             58
#define LOOP                           59
#define EXIT                           60
#define BEGSEQ                         61
#define RECOVER                        62
#define FINALLY                        63
#define IF                             64
#define DOCASE                         65
#define CASE                           66
#define ELSEIF                         67
#define ELSE                           68
#define OTHERWISE                      69
#define STEP                           70
#define RBRACKET                       71
#define AT                             72
#define NUMBER                         73
#define STRING                         74
#define NLSTEXT                        75
#define BINARYX                        76
#define BINARYA                        77
#define TRUE                           78
#define FALSE                          79
#define NIL                            80
#define LBRACE                         81
#define PIPE                           82
#define RBRACE                         83
