#define LOWPRECEDENCE                   1
#define UNEXPECTEDCHAR                  2
#define INVALIDENCODING                 3
#define NL                              4
#define DOT                             5
#define DOTDOT                          6
#define COMMA                           7
#define ASSIGN                          8
#define ADDASS                          9
#define SUBASS                         10
#define MULASS                         11
#define DIVASS                         12
#define MODASS                         13
#define COLCOLASS                      14
#define OR                             15
#define AND                            16
#define NOT                            17
#define EQ                             18
#define EQEQ                           19
#define GTEQ                           20
#define LTEQ                           21
#define EXEQ                           22
#define GT                             23
#define LT                             24
#define DOLLAR                         25
#define PLUS                           26
#define MINUS                          27
#define STAR                           28
#define SLASH                          29
#define MODULO                         30
#define DBSTAR                         31
#define PIPE                           32
#define AMP                            33
#define DBPLUS                         34
#define DBMINUS                        35
#define LBRACKET                       36
#define COLON                          37
#define COLCOL                         38
#define ARROW                          39
#define HIGHPRECEDENCE                 40
#define NAMESPACE                      41
#define USING                          42
#define SYMBOL                         43
#define STATIC                         44
#define CLANG                          45
#define LPAR                           46
#define RPAR                           47
#define CLASS                          48
#define STCLASS                        49
#define NEW                            50
#define ATTRIB                         51
#define METHOD                         52
#define FUNCTION                       53
#define STFUNCTION                     54
#define LOCAL                          55
#define QUIT                           56
#define RETURN                         57
#define END                            58
#define WHILE                          59
#define FOR                            60
#define TO                             61
#define LOOP                           62
#define EXIT                           63
#define BEGSEQ                         64
#define RECOVER                        65
#define FINALLY                        66
#define IF                             67
#define DOCASE                         68
#define CASE                           69
#define ELSEIF                         70
#define ELSE                           71
#define OTHERWISE                      72
#define STEP                           73
#define RBRACKET                       74
#define AT                             75
#define NUMBER                         76
#define STRING                         77
#define NLSTEXT                        78
#define BINARYX                        79
#define BINARYA                        80
#define TRUE                           81
#define FALSE                          82
#define NIL                            83
#define LBRACE                         84
#define RBRACE                         85
