#!/bin/bash
#export GARBAGE=on
#export OREF_SIZE=10000

demo0.exe       >log-demo0
demo1.exe       >log-demo1
demo2.exe       >log-demo2
demo3.exe       >log-demo3

encoding-01.exe >log-encoding-01
encoding-02.exe >log-encoding-02

filter-01.exe   >log-filter-01
filter-02.exe   >log-filter-02
filter-03.exe   >log-filter-03

include-01.exe  >log-include-01
include-02.exe  >log-include-02

input-00.exe    >log-input-00  <x.xml
input-01.exe    >log-input-01
input-02.exe    >log-input-02
input-03.exe    >log-input-03

syntax-00.exe   >log-syntax-00
syntax-01.exe   >log-syntax-01
syntax-02.exe   >log-syntax-02
syntax-03.exe   >log-syntax-03
syntax-04.exe   >log-syntax-04
syntax-05.exe   >log-syntax-05

