#!/bin/bash

echo >log

echo '
---------------------------------------------------------------
demo0: felépíti, majd kiírja az egész dokumentum objektumot
---------------------------------------------------------------' >>log
demo0.exe example.xml >>log


echo '
---------------------------------------------------------------
demo1: megszámlálja az különféle típusú elemeket
---------------------------------------------------------------' >>log
demo1.exe example.xml >>log


echo '
---------------------------------------------------------------
demo2: kilistázza az ügyfeleket
---------------------------------------------------------------' >>log
demo2.exe example.xml >>log


echo '
---------------------------------------------------------------
demo3: kilistázza az számlákat
---------------------------------------------------------------' >>log
demo3.exe example.xml >>log


 
z log

