#!/bin/bash
# Adding the NodeSource APT repository for Debian-based systems.
# Adding  PGP key for verifying packages.
#
#   curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
#   sudo apt-get install nodejs

# then:
#
#   sudo npm install -g less
#   sudo npm install -g minifier
