#!/bin/bash

# DEFAULT_STYLE=src/css/style-push
# DEFAULT_STYLE=src/css/style-grad
  DEFAULT_STYLE=src/css/style-flat

# DEFAULT_COLOR=webapp-cetelem.css
# DEFAULT_COLOR=webapp-grey.css
# DEFAULT_COLOR=webapp-olivedrab.css
# DEFAULT_COLOR=webapp-orange.css
# DEFAULT_COLOR=webapp-seagreen.css
  DEFAULT_COLOR=webapp-slateblue.css
# DEFAULT_COLOR=webapp-tomato.css

  DEFAULT_STYLE_M=src/css/style-mobil
  DEFAULT_COLOR_M=webapp-seagreen.css



rm -f *.gz

# megjegyes: webapp.js.gz, webapp.css.gz 
# Ezek a gz fajlok automatikusan letrejonnek,
# es amig leteznek, a szerver mindig azokat kuldi,
# tehat a valtozasok ervenyre jutasahoz torolni kell.

rm -f webapp.js
touch webapp.js

cat   src/javascript/webapp-core.js         >>webapp.js
cat   src/javascript/webapp-websocket.js    >>webapp.js
cat   src/javascript/webapp-formdata.js     >>webapp.js
cat   src/javascript/webapp-private.js      >>webapp.js
cat   src/javascript/webapp-xlib.js         >>webapp.js
cat   src/javascript/webapp-util.js         >>webapp.js
cat   src/javascript/webapp-alert.js        >>webapp.js
cat   src/javascript/webapp-inp_date.js     >>webapp.js
cat   src/javascript/webapp-inp_number.js   >>webapp.js
cat   src/javascript/webapp-inp_picture.js  >>webapp.js
cat   src/javascript/webapp-inp_regex.js    >>webapp.js
cat   src/javascript/webapp-compat.js       >>webapp.js
cat   src/javascript/webapp-md5.js          >>webapp.js
cat   src/javascript/webapp-password.js     >>webapp.js
cat   src/javascript/webapp-readfile.js     >>webapp.js
cat   src/javascript/combo.js               >>webapp.js
cat   src/javascript/datepicker.js          >>webapp.js
cat   src/javascript/popup.js               >>webapp.js

#exit 0
#set -x

for CSSDIR in src/css/style-*; do
    echo $CSSDIR
    pushd $CSSDIR >/dev/null
    for COLORS in ../colors/colors-*.less; do
        cp $COLORS colors.less
        COLORS=$(echo $COLORS | sed s^.*colors-^^ )
        COLORS=$(echo $COLORS | sed s^.less^^ )
        echo "/*$CSSDIR:$COLORS*/" >webapp-$COLORS.css
        lessc webapp.less >>webapp-$COLORS.css
    done
    rm colors.less
    popd >/dev/null
done


#set -x
cp -p $DEFAULT_STYLE/$DEFAULT_COLOR  webapp.css  #ez a default
cp -p $DEFAULT_STYLE_M/$DEFAULT_COLOR_M  webappm.css  #mobil



# minify --no-comments webapp.js
# minify --no-comments webapp.css
#
# mv webapp.min.js  webapp.js 
# mv webapp.min.css webapp.css 

