#!/bin/bash

#java -jar ~/bin/closure-compiler.jar --help >HELP
#exit


rm -f webapp.js
touch webapp.js


java -jar  ~/bin/closure-compiler.jar --js webapp-core.js         >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-websocket.js    >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-formdata.js     >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-private.js      >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-xlib.js         >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-util.js         >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-inp_date.js     >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-inp_number.js   >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-inp_picture.js  >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-inp_regex.js    >>webapp.js
java -jar  ~/bin/closure-compiler.jar --js webapp-compat.js       >>webapp.js


ls -l webapp.js

