#!/bin/bash
rm -f webapp.js
touch webapp.js

java -jar ~/bin/yuicompressor.jar  webapp-core.js         >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-websocket.js    >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-formdata.js     >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-private.js      >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-xlib.js         >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-util.js         >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-inp_date.js     >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-inp_number.js   >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-inp_picture.js  >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-inp_regex.js    >>webapp.js
java -jar ~/bin/yuicompressor.jar  webapp-compat.js       >>webapp.js

ls -l webapp.js
