#define EXPR                            1
#define SPACE                           2
#define EXCL                            3
#define MINUS                           4
#define PLUS                            5
#define AT                              6
#define LBRACKET                        7
#define RBRACKET                        8
#define SLASH                           9
#define BSLASH                         10
#define DOT                            11
#define PIPE                           12
#define AMP                            13
#define STAR                           14
#define MODULO                         15
#define POWER                          16
#define DOLLAR                         17
#define GT                             18
#define LT                             19
#define COLON                          20
#define EQUAL                          21
#define LPAR                           22
#define RPAR                           23
#define DOTDOT                         24
#define LBRACE                         25
#define RBRACE                         26
#define COMMA                          27
