#!/bin/bash

export CCCDIR=/opt/ccc3

export PATH=$CCCDIR/usr/bin:$PATH
export LD_LIBRARY_PATH=$CCCDIR/usr/lib:$LD_LIBRARY_PATH
export JTERMINAL=$CCCDIR/usr/bin/jterminal.jar
export JTRESOL=low

nohup oggplay.exe "$@" 2>&1 >/dev/null &
