#!/bin/bash
c++app.sh  -sccc"$CCCVER"_xmldom

cp -pf ${BUILD_OBJ}/*.lib $CCCDIR/usr/lib
#cp -pf ${BUILD_OBJ}/*.so  $CCCDIR/usr/lib
 
#so kozvetlen cp helyett mv-vel kerul a helyere,
#hogy az eppen futo programok nem szalljanak el
find ${BUILD_OBJ}/*.so | while read so; do
    cp -pf $so $so.new
    mv $so.new  $CCCDIR/usr/lib/`basename $so`
done
