#!/bin/bash
# FreeBSD-n nem tudja magat felulirni,
# ezert idehozunk belole egy peldanyt.

EXE=$CCCDIR/usr/bin/$CCCUNAME
cp -p $EXE/build.exe .
export PATH=.:$PATH

bapp_unix_.b  "BUILD_EXE=$EXE" "BUILD_SHR=static"

rm build.exe
#ldd `which build.exe`
