#!/bin/bash

if ! test -f log-data; then
    data.exe
fi

export CCCTERM_CONNECT="$CCCDIR/usr/bin/$CCCUNAME/ncterm.exe"
echo -e "\e]12;darkgreen\a"  # set cursor color
echo -e "\e]12;brown\a"  # set cursor color

tv.exe log-data

