#define LOWPRECEDENCE                   1
#define UNEXPECTEDCHAR                  2
#define INVALIDENCODING                 3
#define NL                              4
#define DOT                             5
#define DOTDOT                          6
#define COMMA                           7
#define ASSIGN                          8
#define ADDASS                          9
#define SUBASS                         10
#define MULASS                         11
#define DIVASS                         12
#define MODASS                         13
#define OR                             14
#define AND                            15
#define NOT                            16
#define EQ                             17
#define EQEQ                           18
#define GTEQ                           19
#define LTEQ                           20
#define EXEQ                           21
#define GT                             22
#define LT                             23
#define DOLLAR                         24
#define PLUS                           25
#define MINUS                          26
#define STAR                           27
#define SLASH                          28
#define MODULO                         29
#define DBSTAR                         30
#define DBPLUS                         31
#define DBMINUS                        32
#define LBRACKET                       33
#define COLON                          34
#define ARROW                          35
#define HIGHPRECEDENCE                 36
#define NAMESPACE                      37
#define USING                          38
#define SYMBOL                         39
#define STATIC                         40
#define LPAR                           41
#define RPAR                           42
#define CLASS                          43
#define NEW                            44
#define ATTRIB                         45
#define METHOD                         46
#define FUNCTION                       47
#define STFUNCTION                     48
#define LOCAL                          49
#define QUIT                           50
#define RETURN                         51
#define END                            52
#define WHILE                          53
#define FOR                            54
#define TO                             55
#define LOOP                           56
#define EXIT                           57
#define BEGSEQ                         58
#define RECOVER                        59
#define FINALLY                        60
#define IF                             61
#define DOCASE                         62
#define CASE                           63
#define ELSEIF                         64
#define ELSE                           65
#define OTHERWISE                      66
#define STEP                           67
#define AT                             68
#define NUMBER                         69
#define STRING                         70
#define NLSTEXT                        71
#define BINARYX                        72
#define BINARYA                        73
#define TRUE                           74
#define FALSE                          75
#define NIL                            76
#define LBRACE                         77
#define PIPE                           78
#define RBRACE                         79
#define RBRACKET                       80
