#define LOWPRECEDENCE                   1
#define UNEXPECTEDCHAR                  2
#define INVALIDENCODING                 3
#define NL                              4
#define DOT                             5
#define COMMA                           6
#define ASSIGN                          7
#define ADDASS                          8
#define SUBASS                          9
#define MULASS                         10
#define DIVASS                         11
#define MODASS                         12
#define OR                             13
#define AND                            14
#define NOT                            15
#define EQ                             16
#define EQEQ                           17
#define GTEQ                           18
#define LTEQ                           19
#define EXEQ                           20
#define GT                             21
#define LT                             22
#define DOLLAR                         23
#define PLUS                           24
#define MINUS                          25
#define STAR                           26
#define SLASH                          27
#define MODULO                         28
#define DBSTAR                         29
#define DBPLUS                         30
#define DBMINUS                        31
#define LBRACKET                       32
#define COLON                          33
#define ARROW                          34
#define HIGHPRECEDENCE                 35
#define NAMESPACE                      36
#define USING                          37
#define SYMBOL                         38
#define STATIC                         39
#define LPAR                           40
#define RPAR                           41
#define CLASS                          42
#define NEW                            43
#define ATTRIB                         44
#define METHOD                         45
#define FUNCTION                       46
#define STFUNCTION                     47
#define LOCAL                          48
#define QUIT                           49
#define RETURN                         50
#define END                            51
#define WHILE                          52
#define FOR                            53
#define TO                             54
#define LOOP                           55
#define EXIT                           56
#define BEGSEQ                         57
#define RECOVER                        58
#define FINALLY                        59
#define IF                             60
#define DOCASE                         61
#define CASE                           62
#define ELSEIF                         63
#define ELSE                           64
#define OTHERWISE                      65
#define STEP                           66
#define AT                             67
#define NUMBER                         68
#define STRING                         69
#define NLSTEXT                        70
#define BINARYX                        71
#define BINARYA                        72
#define TRUE                           73
#define FALSE                          74
#define NIL                            75
#define LBRACE                         76
#define PIPE                           77
#define RBRACE                         78
#define RBRACKET                       79
