#define LOWPRECEDENCE                   1
#define UNEXPECTEDCHAR                  2
#define INVALIDENCODING                 3
#define NL                              4
#define DOT                             5
#define DOTDOT                          6
#define COMMA                           7
#define ASSIGN                          8
#define ADDASS                          9
#define SUBASS                         10
#define MULASS                         11
#define DIVASS                         12
#define MODASS                         13
#define COLCOLASS                      14
#define OR                             15
#define AND                            16
#define NOT                            17
#define EQ                             18
#define EQEQ                           19
#define GTEQ                           20
#define LTEQ                           21
#define EXEQ                           22
#define GT                             23
#define LT                             24
#define DOLLAR                         25
#define PLUS                           26
#define MINUS                          27
#define STAR                           28
#define SLASH                          29
#define MODULO                         30
#define DBSTAR                         31
#define DBPLUS                         32
#define DBMINUS                        33
#define LBRACKET                       34
#define COLON                          35
#define COLCOL                         36
#define ARROW                          37
#define HIGHPRECEDENCE                 38
#define NAMESPACE                      39
#define USING                          40
#define SYMBOL                         41
#define STATIC                         42
#define LPAR                           43
#define RPAR                           44
#define CLASS                          45
#define NEW                            46
#define ATTRIB                         47
#define METHOD                         48
#define FUNCTION                       49
#define STFUNCTION                     50
#define LOCAL                          51
#define QUIT                           52
#define RETURN                         53
#define END                            54
#define WHILE                          55
#define FOR                            56
#define TO                             57
#define LOOP                           58
#define EXIT                           59
#define BEGSEQ                         60
#define RECOVER                        61
#define FINALLY                        62
#define IF                             63
#define DOCASE                         64
#define CASE                           65
#define ELSEIF                         66
#define ELSE                           67
#define OTHERWISE                      68
#define STEP                           69
#define AT                             70
#define NUMBER                         71
#define STRING                         72
#define NLSTEXT                        73
#define BINARYX                        74
#define BINARYA                        75
#define TRUE                           76
#define FALSE                          77
#define NIL                            78
#define LBRACE                         79
#define PIPE                           80
#define RBRACE                         81
#define RBRACKET                       82
