#!/bin/bash
bapp_unix0.b  -sccc3_sql2_postgres

if [ -s error ]; then
    list error &
else
    cp -pf obj$CCCBIN/*.lib  $CCCDIR/usr/lib/$CCCBIN
    cp -pf obj$CCCBIN/*.so   $CCCDIR/usr/lib/$CCCBIN
    cp -pf sql.ch  $CCCDIR/usr/include
fi
