#!/bin/bash

PORT=46000
APPL=empty.exe

echo $PORT

# 1) egyszerű listener ssl nélkül
# jtlisten.exe $PORT $APPL -jtdebug


# 2) egyszerű listener ssl forwardinggal (kell hozzá a server.pem filé)
#jtlisten.exe $PORT sslforward.exe $APPL -jtdebug


# 3) önálló program indítás 
 $APPL -jtauto -jtdebug


# 4) önálló program indítás 
# $APPL -jtsocket :$PORT &
# java -jar $JTERMINAL localhost $PORT 


# 5) sokszori indítás jtstart-tal
# először jtstart.exe-t indítjuk,
# ebben csak egy gomb van, ami indítja a paraméterként kapott programot,
# ennek az az értelme, hogy nem kell várni a Jáva betöltődésére,
# miközben a tesztelt alkalmazást fordítgatjuk
# jtstart.exe "$APPL"  
