#!/bin/bash
rm -f log-content
for LIB in *.lib; do
    if [ $LIB == "setup.lib" ]; then
        :
    else
        echo ================================================================ $LIB  >>log-content
        libcontent.exe    $LIB  >>log-content
    fi
done