#!/bin/bash

mkdir -p ${BUILD_OBJ}
pkg-config --cflags gtk+-2.0  >${BUILD_OBJ}/gtk-cflags
pkg-config --libs   gtk+-2.0  >${BUILD_OBJ}/gtk-libs
echo -Wno-deprecated-declarations >>${BUILD_OBJ}/gtk-cflags

cccapp.sh  @parfile.bld  
