#!/bin/bash

mkdir -p ${BUILD_OBJ}

pkg-config --cflags gtk+-3.0             >${BUILD_OBJ}/gtk-cflags
echo -DGDK_DISABLE_DEPRECATED           >>${BUILD_OBJ}/gtk-cflags
#echo -DGTK_DISABLE_DEPRECATED           >>${BUILD_OBJ}/gtk-cflags
echo -DGTK_DISABLE_SINGLE_INCLUDES      >>${BUILD_OBJ}/gtk-cflags
echo -DGSEAL_ENABLE                     >>${BUILD_OBJ}/gtk-cflags

echo -DCOMPILE_TERMINAL                 >>${BUILD_OBJ}/gtk-cflags
echo -Wno-deprecated-declarations       >>${BUILD_OBJ}/gtk-cflags

pkg-config --libs   gtk+-3.0            >${BUILD_OBJ}/gtk-libs

c++app.sh  @parfile.bld


